[build]
  base = "frontend/myapp"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://happyrenting.netlify.app/*"
  to = "https://happyrenting.co.in/:splat"
  status = 301
  force = true
