import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

export interface OwnerReportItem {
  _id: string;
  category: string;
  title?: string;
  amount: number;
  isRecurring: boolean;
  expenseDate?: string;
  propertyId?: { _id: string; name: string } | string;
}

export interface OwnerReportData {
  month: string;
  monthLabel: string;
  income: number;
  expenses: number;
  netProfit: number;
  expenseCount: number;
  propertyName: string;
  items: OwnerReportItem[];
}

const CATEGORY_LABEL: Record<string, string> = {
  maintenance: 'Maintenance', electricity: 'Electricity', water: 'Water',
  society: 'Society', repairs: 'Repairs', cleaning: 'Cleaning', internet: 'Internet', misc: 'Misc',
};

const formatINR = (n: number) => '₹' + (n ?? 0).toLocaleString('en-IN');

export async function generateOwnerReportPdf(data: OwnerReportData): Promise<void> {
  const rows = data.items
    .map(
      (e) => `
      <tr>
        <td>${e.expenseDate ?? ''}</td>
        <td>${CATEGORY_LABEL[e.category] ?? e.category}</td>
        <td>${e.title ?? '—'}</td>
        <td>${typeof e.propertyId === 'object' && e.propertyId ? e.propertyId.name : '—'}</td>
        <td class="num">${formatINR(e.amount)}</td>
      </tr>`
    )
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; background-color: #f8fafc; }
        .box { max-width: 720px; margin: auto; background: white; padding: 32px; border-radius: 12px; border: 1px solid #e2e8f0; }
        .header { background: #2563EB; color: white; padding: 24px; border-radius: 8px; margin-bottom: 28px; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; }
        .header p { margin: 6px 0 0 0; opacity: 0.85; font-size: 13px; }
        .summary { display: flex; justify-content: space-between; gap: 12px; margin-bottom: 24px; }
        .card { flex: 1; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; text-align: center; }
        .card .lbl { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.4px; }
        .card .val { font-size: 20px; font-weight: 800; margin-top: 4px; }
        .income { color: #16a34a; } .expense { color: #ef4444; } .profit { color: #2563EB; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { background: #f1f5f9; text-align: left; padding: 8px; color: #475569; text-transform: uppercase; font-size: 10px; letter-spacing: 0.4px; }
        td { padding: 8px; border-bottom: 1px solid #f1f5f9; }
        .num { text-align: right; font-weight: 600; }
        .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #94a3b8; }
      </style>
    </head>
    <body>
      <div class="box">
        <div class="header">
          <h1>Happy Renting</h1>
          <p>Monthly Report — ${data.monthLabel} · ${data.propertyName}</p>
        </div>
        <div class="summary">
          <div class="card"><div class="lbl">Rent Collected</div><div class="val income">${formatINR(data.income)}</div></div>
          <div class="card"><div class="lbl">Expenses</div><div class="val expense">${formatINR(data.expenses)}</div></div>
          <div class="card"><div class="lbl">Net Profit</div><div class="val profit">${formatINR(data.netProfit)}</div></div>
        </div>
        <h3 style="font-size:14px; margin: 0 0 8px;">Expense Breakdown (${data.expenseCount})</h3>
        <table>
          <thead>
            <tr><th>Date</th><th>Category</th><th>Title</th><th>Property</th><th class="num">Amount</th></tr>
          </thead>
          <tbody>${rows || '<tr><td colspan="5" style="text-align:center; color:#94a3b8;">No expenses recorded</td></tr>'}</tbody>
        </table>
        <div class="footer">
          Generated by Happy Renting — Property & Tenancy Management System<br/>
          Generated on ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
        </div>
      </div>
    </body>
    </html>
  `;

  const { base64 } = await Print.printToFileAsync({ html, base64: true });
  if (!base64) throw new Error('Failed to generate PDF');

  const filename = `Report_${data.month}.pdf`;
  const destinationUri = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.writeAsStringAsync(destinationUri, base64, { encoding: FileSystem.EncodingType.Base64 });

  await Sharing.shareAsync(destinationUri, {
    mimeType: 'application/pdf',
    dialogTitle: `Monthly Report - ${data.monthLabel}`,
    UTI: 'com.adobe.pdf',
  });
}