// One-shot script: adds Hindi translations for all owner portal keys.
// Skips keys that already exist in the target file.
const fs = require('fs');
const path = require('path');

const TARGETS = ['hi', 'kn', 'ml', 'ta', 'te'];

// ─── Hindi (hi) ────────────────────────────────────────────────────────────
const HI = {
  commonOwner: {
    saveChanges: 'बदलाव सहेजें',
    remove: 'हटाएं',
    cancel: 'रद्द करें',
    error: 'त्रुटि',
    verified: 'सत्यापित',
    rejected: 'अस्वीकृत',
    property: 'प्रॉपर्टी',
    floor: 'मंज़िल',
    add: 'जोड़ें',
    edit: 'संपादित करें',
    delete: 'मिटाएं',
    yes: 'हाँ',
    no: 'नहीं',
    notes: 'टिप्पणियाँ',
    room: 'कमरा',
    months: 'महीने',
  },
  drawer: {
    ownerDashboard: 'डैशबोर्ड',
    ownerProperties: 'प्रॉपर्टी',
    ownerTenants: 'किरायेदार',
    ownerAddTenant: 'किरायेदार जोड़ें',
    ownerPayments: 'भुगतान',
    ownerApprovals: 'लंबित स्वीकृतियाँ',
    ownerComplaints: 'शिकायतें',
    ownerExpenses: 'खर्चे',
    ownerReports: 'रिपोर्ट',
    ownerNotifications: 'सूचनाएँ',
    helpCenter: 'सहायता केंद्र',
    about: 'Happy Renting के बारे में',
    visitWebsite: 'वेबसाइट देखें',
    rateApp: 'ऐप को रेट करें',
    shareApp: 'Happy Renting शेयर करें',
    shareMessage: 'Happy Renting के साथ किराया, बिल और अपनी प्रॉपर्टी आसानी से मैनेज करें! ऐप डाउनलोड करें: https://play.google.com/store/apps/details?id=co.in.happyrenting.tenant',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    logout: 'लॉग आउट',
    logoutConfirmTitle: 'लॉग आउट',
    logoutConfirmMsg: 'क्या आप सच में लॉग आउट करना चाहते हैं?',
    shareErrorMsg: 'ऐप लिंक शेयर नहीं हो सका। कृपया फिर कोशिश करें।',
    ownerWorkspace: 'मालिक कार्यस्थल',
    tenantWorkspace: 'किरायेदार कार्यस्थल',
  },
  dashboard: {
    title: 'डैशबोर्ड',
    welcome: 'वापसी पर स्वागत है, {{name}}',
    totalCollected: 'कुल संग्रह',
    today: 'आज',
    overdue: 'अतिदेय',
    outstanding: 'बकाया',
    netCollectionMonth: 'शुद्ध संग्रह (इस माह)',
    collected: 'संग्रहित',
    expenses: 'खर्चे',
    entries: 'प्रविष्टियाँ',
    overview: 'सारांश',
    properties: 'प्रॉपर्टी',
    rooms: 'कमरे',
    activeTenants: 'सक्रिय किरायेदार',
    occupancy: 'अधिभोग',
    paidBills: 'भुगतान किए गए बिल',
    overdueBills: 'अतिदेय बिल',
    paymentBreakdown: 'भुगतान विवरण',
    pendingBills: 'लंबित बिल',
    partialPayments: 'आंशिक भुगतान',
    overdueBillsBreakdown: 'अतिदेय बिल',
    totalOutstanding: 'कुल बकाया',
    seeAll: 'सभी देखें',
    loadError: 'आँकड़े लोड नहीं हो सके। पुनः प्रयास के लिए नीचे खींचें।',
  },
  properties: {
    title: 'प्रॉपर्टी',
    count_one: '{{count}} प्रॉपर्टी',
    count_other: '{{count}} प्रॉपर्टीज़',
    add: 'जोड़ें',
    addBtn: 'प्रॉपर्टी जोड़ें',
    addTitle: 'प्रॉपर्टी जोड़ें',
    editTitle: 'प्रॉपर्टी संपादित करें',
    fieldName: 'प्रॉपर्टी का नाम *',
    fieldAddress: 'पता *',
    fieldCity: 'शहर',
    placeholderName: 'जैसे: ग्रीन वैली अपार्टमेंट',
    placeholderAddress: 'गली, क्षेत्र, लैंडमार्क…',
    placeholderCity: 'जैसे: चेन्नई',
    cancel: 'रद्द करें',
    save: 'बदलाव सहेजें',
    saveAdd: 'प्रॉपर्टी जोड़ें',
    removeTitle: 'प्रॉपर्टी हटाएं',
    removeMsg: '"{{name}}" हटाएं? इससे प्रॉपर्टी निष्क्रिय हो जाएगी। किरायेदार और कमरे का डेटा सुरक्षित रहेगा।',
    errCreate: 'प्रॉपर्टी बनाने में विफल।',
    errUpdate: 'प्रॉपर्टी अपडेट करने में विफल।',
    errRemove: 'प्रॉपर्टी हटाने में विफल।',
    loading: 'प्रॉपर्टी लोड हो रही हैं…',
    emptyTitle: 'अभी कोई प्रॉपर्टी नहीं',
    emptyBody: 'पहली प्रॉपर्टी बनाने के लिए जोड़ें बटन दबाएं।',
    statsTotal: 'कुल',
    statsOccupied: 'कब्ज़े में',
    statsVacant: 'खाली',
    statsOccupancy: 'अधिभोग',
    noRooms: 'अभी कोई कमरा नहीं। कमरे जोड़ने के लिए कार्ड पर टैप करें।',
  },
  rooms: {
    title: 'कमरे',
    add: 'जोड़ें',
    addBtn: 'कमरा जोड़ें',
    addTitle: 'कमरा जोड़ें',
    editTitle: 'कमरा संपादित करें',
    fieldRoomNumber: 'कमरे का नंबर *',
    fieldFloor: 'मंज़िल',
    fieldCapacity: 'क्षमता *',
    fieldMonthlyRent: 'मासिक किराया (₹)',
    fieldSecurityDeposit: 'सुरक्षा जमा (₹)',
    fieldDescription: 'विवरण',
    placeholderRoomNumber: 'जैसे: 101',
    placeholderFloor: 'जैसे: ग्राउंड',
    placeholderDescription: 'वैकल्पिक नोट',
    infoOccupied: '{{occupied}}/{{capacity}} कब्ज़े में · क्षमता अधिभोग से कम नहीं की जा सकती',
    errCapacityMin: 'क्षमता कम से कम {{min}} होनी चाहिए',
    cancel: 'रद्द करें',
    saveChanges: 'बदलाव सहेजें',
    saveAdd: 'कमरा जोड़ें',
    removeTitle: 'कमरा हटाएं',
    removeMsg: 'कमरा {{number}} हटाएं? यदि कमरा खाली है तो इसे पूर्ववत नहीं किया जा सकता।',
    errCreate: 'कमरा बनाने में विफल।',
    errUpdate: 'कमरा अपडेट करने में विफल।',
    errRemove: 'कमरा हटाने में विफल।',
    emptyTitle: 'अभी कोई कमरा नहीं',
    emptySub: 'पहला कमरा बनाने के लिए जोड़ें दबाएं।',
    propertyFallback: 'प्रॉपर्टी',
    count_one: '{{count}} कमरा',
    count_other: '{{count}} कमरे',
    floorPrefix: '· मंज़िल {{floor}}',
    rent: 'किराया {{amount}}',
    deposit: 'जमा {{amount}}',
    badgeFull: 'भरा हुआ',
    badgeAvailable: 'उपलब्ध',
    occupiedCount: '{{occupied}}/{{capacity}} कब्ज़े में',
  },
  tenants: {
    title: 'किरायेदार',
    add: 'जोड़ें',
    addBtn: 'किरायेदार जोड़ें',
    count_one: '{{count}} कुल',
    count_other: '{{count}} कुल',
    countActive_one: '{{count}} सक्रिय',
    countActive_other: '{{count}} सक्रिय',
    countVacated_one: '{{count}} खाली हुए',
    countVacated_other: '{{count}} खाली हुए',
    tabActive: 'सक्रिय',
    tabVacated: 'खाली हुए',
    tabAll: 'सभी',
    searchPlaceholder: 'नाम, कमरा, प्रॉपर्टी से खोजें…',
    emptyNoSearch: 'कोई परिणाम नहीं मिला',
    emptyNoTenants: 'कोई किरायेदार नहीं',
    emptyNoActive: 'कोई सक्रिय किरायेदार नहीं',
    emptyNoVacated: 'कोई खाली किरायेदार नहीं',
    detailRoom: 'कमरा',
    detailProperty: 'प्रॉपर्टी',
    detailMonthlyRent: 'मासिक किराया',
    detailMoveIn: 'प्रवेश तिथि',
    detailExit: 'निकास तिथि',
    detailPhone: 'फ़ोन',
    detailIdNumber: 'आईडी नंबर',
    detailSecurityDeposit: 'सुरक्षा जमा',
    detailAdvancePaid: 'अग्रिम भुगतान',
    detailNotes: 'टिप्पणियाँ',
    detailEdit: 'विवरण संपादित करें',
    detailMoveOut: 'किरायेदार को बाहर करें',
    detailReverse: 'मूव-आउट पूर्ववत करें',
    refundDue: 'रिफ़ंड देय',
    refundSettled: 'रिफ़ंड चुकता',
    markSettled: 'चुकता मार्क करें',
    statusActive: 'सक्रिय',
    statusVacated: 'खाली हुआ',
    statusPendingDeletion: 'हटाने के लिए लंबित',
    since: '{{date}} से',
    moveOutTitle: 'किरायेदार को बाहर करें',
    moveOutFieldExitDate: 'निकास तिथि *',
    moveOutFieldNotes: 'टिप्पणियाँ (वैकल्पिक)',
    moveOutPlaceholderNotes: 'मूव-आउट का कारण…',
    moveOutConfirm: 'मूव-आउट पुष्टि करें',
    moveOutAlertTitle: 'हो गया',
    moveOutAlertMsg: 'किरायेदार को सफलतापूर्वक बाहर किया गया।',
    moveOutErr: 'मूव-आउट विफल। कृपया फिर कोशिश करें।',
    moveOutEmptyExitDate: 'निकास तिथि',
    reverseAlertTitle: 'मूव-आउट पूर्ववत करें',
    reverseAlertMsg: '{{name}} (कमरा {{room}}) को वापस सक्रिय करें? इससे कमरा फिर से कब्ज़े में आ जाएगा।',
    reverseAlertRestore: 'पुनर्स्थापित करें',
    reverseDeletedTitle: 'मूव-आउट पूर्ववत नहीं किया जा सकता',
    reverseDeletedMsg: 'इस किरायेदार का खाता हटा दिया गया है। मूव-आउट पूर्ववत नहीं किया जा सकता।',
    reverseOk: 'ठीक है',
    reverseDoneTitle: 'पूर्ववत किया गया',
    reverseDoneMsg: 'किरायेदार को सक्रिय स्थिति में बहाल किया गया।',
    reverseErr: 'पूर्ववत करने में विफल। कृपया फिर कोशिश करें।',
    editTitle: 'किरायेदार संपादित करें',
    editTabFinance: 'वित्त',
    editTabProfile: 'प्रोफ़ाइल',
    editErrAdvanceDeposit: 'अग्रिम भुगतान सुरक्षा जमा से कम या बराबर होना चाहिए।',
    editFieldTargetDeposit: 'लक्ष्य सुरक्षा जमा (कुल ₹)',
    editFieldPaid: 'वर्तमान में भुगतान किया (₹)',
    editFieldFullName: 'पूरा नाम',
    editFieldEmail: 'ईमेल',
    editFieldPhone: 'फ़ोन',
    editFieldIdNumber: 'आईडी नंबर',
    editPlaceholderDeposit: 'अपेक्षित कुल राशि',
    editHintDeposit: 'किरायेदार से अपेक्षित कुल राशि।',
    editPlaceholderPaid: '0',
    editPlaceholderName: 'किरायेदार का पूरा नाम',
    editPlaceholderEmail: 'tenant@example.com',
    editPlaceholderPhone: 'किरायेदार का फ़ोन',
    editPlaceholderId: 'आधार / सरकारी आईडी नंबर',
    editSavedTitle: 'सहेजा गया',
    editSavedMsg: 'किरायेदार विवरण अपडेट किया गया।',
    editErr: 'अपडेट विफल। कृपया फिर कोशिश करें।',
    refundTitle: 'रिफ़ंड चुकता मार्क करें',
    refundFieldNote: 'टिप्पणी (वैकल्पिक)',
    refundPlaceholderNote: 'इस रिफ़ंड के लिए वैकल्पिक नोट…',
    refundConfirm: 'चुकता मार्क करें',
    refundAlertTitle: 'चुकता',
    refundAlertMsg: 'रिफ़ंड चुकता मार्क किया गया।',
    refundErr: 'रिफ़ंड चुकता करने में विफल। कृपया फिर कोशिश करें।',
  },
  addTenant: {
    title: 'किरायेदार जोड़ें',
    sub: 'किरायेदार को कमरे में लाएं',
    sectionRoom: '1. कमरा असाइन करें',
    sectionTenant: '2. किरायेदार',
    sectionDetails: '3. लीज़ विवरण',
    selectRoomPlaceholder: 'खाली कमरा चुनें…',
    errRoomFull: 'यह कमरा भरा हुआ है।',
    segmentExisting: 'मौजूदा उपयोगकर्ता',
    segmentNew: 'नया बनाएं',
    selectUserPlaceholder: 'पंजीकृत उपयोगकर्ता चुनें…',
    labelFullName: 'पूरा नाम *',
    labelEmail: 'ईमेल *',
    placeholderName: 'किरायेदार का नाम',
    placeholderEmail: 'tenant@email.com',
    btnSendOtp: 'OTP भेजें',
    labelOtp: 'OTP',
    placeholderOtp: '6-अंकीय',
    btnVerify: 'सत्यापित करें',
    verified: 'ईमेल सत्यापित',
    labelPassword: 'अस्थायी पासवर्ड *',
    placeholderPassword: 'पासवर्ड सेट करें',
    passwordHint: 'न्यूनतम 8 अक्षर, बड़े-छोटे अक्षर, संख्या व विशेष वर्ण (@$!%*?&) आवश्यक',
    btnAccountCreated: 'खाता बनाया गया',
    btnCreateAccount: 'खाता बनाएं',
    labelPhone: 'फ़ोन *',
    placeholderPhone: 'किरायेदार का फ़ोन',
    labelIdNumber: 'आईडी नंबर',
    placeholderIdNumber: 'आधार / सरकारी आईडी नंबर',
    labelJoinDate: 'जुड़ने की तिथि *',
    placeholderJoinDate: 'तिथि चुनें…',
    labelSecurityDeposit: 'सुरक्षा जमा (₹)',
    labelAdvancePaid: 'अग्रिम भुगतान (₹)',
    labelNotes: 'टिप्पणियाँ',
    placeholderNotes: 'वैकल्पिक नोट',
    btnSubmit: 'किरायेदार जोड़ें',
    alertRegisterTitle: 'पंजीकरण विफल',
    alertRegisterMsg: 'खाता बनाने में विफल।',
    alertMissingTitle: 'विवरण अधूरा',
    alertMissingName: 'कृपया किरायेदार का नाम दर्ज करें।',
    alertInvalidNameTitle: 'अमान्य नाम',
    alertInvalidNameMsg: 'नाम कम से कम 2 अक्षर का होना चाहिए।',
    alertWeakPwTitle: 'कमज़ोर पासवर्ड',
    alertWeakPwMin: 'पासवर्ड कम से कम 8 अक्षर का होना चाहिए।',
    alertWeakPwChars: 'पासवर्ड में बड़े-छोटे अक्षर, संख्या व विशेष वर्ण (@$!%*?&) होने चाहिए।',
    alertDone: 'हो गया',
    alertDoneMsg: 'किरायेदार सफलतापूर्वक जोड़ा गया।',
    alertErr: 'किरायेदार जोड़ने में विफल।',
    selectRoomTitle: 'कमरा चुनें',
    selectUserTitle: 'उपयोगकर्ता चुनें',
    userAlreadyActive: 'पहले से सक्रिय किरायेदार',
    selectDateTitle: 'जुड़ने की तिथि चुनें',
    occupancySuffix: '{{occupied}}/{{capacity}} कब्ज़े में',
    rentPerMonth: '{{amount}}/माह',
  },
  payments: {
    title: 'भुगतान',
    headerSub: 'आज संग्रहित ₹{{amount}}',
    stripOverdue: 'अतिदेय',
    stripPending: 'लंबित',
    stripCollected: 'संग्रहित',
    tabAll: 'सभी',
    tabOverdue: 'अतिदेय',
    tabPending: 'लंबित',
    tabPartial: 'आंशिक',
    tabPaid: 'भुगतान किया गया',
    searchPlaceholder: 'किरायेदार, कमरा, महीना से खोजें…',
    emptyNoSearch: 'कोई परिणाम नहीं मिला',
    emptyNoRecords: 'कोई {{status}} रिकॉर्ड नहीं',
    statusPending: 'लंबित',
    statusPartial: 'आंशिक',
    statusOverdue: 'अतिदेय',
    statusPaid: 'भुगतान किया गया',
    amountTotal: 'कुल',
    amountPaid: 'भुगतान',
    amountRemaining: 'शेष',
    proofAwaiting: 'भुगतान प्रमाण सत्यापन की प्रतीक्षा में',
    btnVerify: 'सत्यापित करें',
    btnReject: 'अस्वीकार करें',
    verifyAlertTitle: 'भुगतान सत्यापित करें',
    verifyAlertMsg: 'क्या इस भुगतान प्रमाण की पुष्टि कर किरायेदार को जमा करें?',
    verifyAlertConfirm: 'सत्यापित करें',
    verifiedAlertTitle: 'सत्यापित',
    verifiedAlertMsg: 'भुगतान सत्यापित कर जमा किया गया।',
    rejectedAlertTitle: 'अस्वीकृत',
    rejectedAlertMsg: 'भुगतान प्रमाण अस्वीकार किया गया। किरायेदार को सूचित किया जाएगा।',
    errVerify: 'सत्यापन विफल।',
    errReject: 'अस्वीकार विफल।',
    rejectModalTitle: 'भुगतान अस्वीकार करें',
    rejectModalSub: 'कारण बताएं ताकि किरायेदार को पता चले कि उनका प्रमाण क्यों अस्वीकार किया गया।',
    rejectPlaceholder: 'जैसे: धुंधली छवि, गलत राशि…',
    btnCancel: 'रद्द करें',
  },
  approvals: {
    title: 'लंबित स्वीकृतियाँ',
    count_one: '{{count}} सत्यापन की प्रतीक्षा में',
    count_other: '{{count}} सत्यापन की प्रतीक्षा में',
    allCaughtTitle: 'सब हो गया!',
    allCaughtSub: 'कोई भुगतान प्रमाण स्वीकृति की प्रतीक्षा में नहीं।',
    btnApprove: 'स्वीकृत करें',
    btnReject: 'अस्वीकार',
    rejectTitle: 'भुगतान अस्वीकार करें',
    rejectSub: 'कारण बताएं ताकि किरायेदार को पता चले कि उनका प्रमाण क्यों अस्वीकार किया गया।',
    rejectPlaceholder: 'जैसे: गलत राशि, धुंधली छवि…',
    btnCancel: 'रद्द करें',
    errVerify: 'सत्यापन विफल।',
    errReject: 'अस्वीकार विफल।',
  },
  transactions: {
    fallbackTitle: 'भुगतान',
    totalCollected: 'कुल संग्रह',
    floatBanner: 'अस्थायी शेष: {{amount}} आगे बढ़ाया जा रहा है',
    proofAwaiting: 'भुगतान प्रमाण सत्यापन की प्रतीक्षा में',
    sectionTransactions: 'लेन-देन',
    emptyTitle: 'अभी तक कोई लेन-देन दर्ज नहीं।',
    btnRecordPayment: 'भुगतान दर्ज करें',
    addPaymentTitle: 'भुगतान दर्ज करें',
    fieldAmount: 'राशि (₹) *',
    fieldMethod: 'भुगतान विधि *',
    methodCash: 'नकद',
    methodUpi: 'UPI',
    methodBank: 'बैंक',
    methodCheque: 'चेक',
    fieldDate: 'भुगतान तिथि *',
    placeholderDate: 'YYYY-MM-DD',
    fieldNotes: 'टिप्पणियाँ',
    placeholderNotes: 'वैकल्पिक संदर्भ',
    btnAttachProof: 'भुगतान प्रमाण जोड़ें (वैकल्पिक)',
    btnCancel: 'रद्द करें',
    btnRecord: 'भुगतान दर्ज करें',
    btnVerify: 'सत्यापित करें',
    btnReject: 'अस्वीकार',
    btnReverse: 'इस भुगतान को उलटें',
    btnUndoReversal: 'उलटना पूर्ववत करें',
    refLabel: 'रेफ़: {{ref}}',
    recordedBy: '{{name}} ({{role}}) द्वारा दर्ज',
    alertPermissionTitle: 'अनुमति',
    alertPermissionMsg: 'प्रमाण जोड़ने के लिए गैलरी अनुमति आवश्यक है।',
    alertErrRecord: 'भुगतान दर्ज करने में विफल।',
    errVerify: 'सत्यापन विफल।',
    errReject: 'अस्वीकार विफल।',
    errReverse: 'उलटना विफल।',
    errUndo: 'उलटना पूर्ववत करने में विफल।',
    errLoad: 'भुगतान विवरण लोड नहीं हो सका',
    btnRetry: 'पुनः प्रयास',
    reversedAlertTitle: 'उलटा गया',
    reversedAlertMsg: 'भुगतान उलटा दिया गया।',
    undoneAlertTitle: 'पूर्ववत किया गया',
    undoneAlertMsg: 'उलटना पूर्ववत किया गया। भुगतान रिकॉर्ड पर पुनः लागू।',
    undoTitle: 'उलटना पूर्ववत करें',
    undoMsg: '{{amount}} को वापस इस रिकॉर्ड पर लागू करें?',
    undoConfirm: 'पूर्ववत करें',
    reverseTitle: 'भुगतान उलटें',
    reverseSub: '{{date}} को {{amount}} दर्ज किया गया',
    reversePlaceholder: 'उलटने का कारण (आवश्यक)',
    reverseBtn: 'उलटें',
    btnCancel2: 'रद्द करें',
    statusCompleted: 'पूर्ण',
    statusVerifying: 'सत्यापन जारी',
    statusReversed: 'उलटा गया',
    statusFailed: 'विफल',
    floatMovedOut: 'अस्थायी राशि −{{amount}} इस माह से बाहर ले जाई गई',
    floatMovedIn: 'अस्थायी राशि +{{amount}} इस माह में लाई गई',
  },
  complaints: {
    title: 'शिकायतें',
    count_one: '{{count}} शिकायत',
    count_other: '{{count}} शिकायतें',
    tabAll: 'सभी',
    tabOpen: 'खुली',
    tabInProgress: 'जारी',
    tabResolved: 'हल हुई',
    searchPlaceholder: 'शीर्षक या किरायेदार से खोजें…',
    emptyNoSearch: 'कोई परिणाम नहीं मिला',
    emptyDefault: 'यहाँ कोई शिकायत नहीं',
    statusOpen: 'खुली',
    statusInProgress: 'जारी',
    statusResolved: 'हल हुई',
    statusRejected: 'अस्वीकृत',
    statusClosed: 'बंद',
    priorityLow: 'कम',
    priorityMedium: 'मध्यम',
    priorityHigh: 'उच्च',
    priorityUrgent: 'अत्यावश्यक',
    noLocation: 'कोई स्थान नहीं',
  },
  complaintDetail: {
    title: 'शिकायत',
    errLoad: 'शिकायत लोड नहीं हो सकी',
    btnRetry: 'पुनः प्रयास',
    badgePrioritySuffix: '{{label}} प्राथमिकता',
    resolutionNotes: 'समाधान नोट्स',
    sectionUpdateStatus: 'स्थिति अपडेट करें',
    fieldResolutionNotes: 'समाधान नोट्स *',
    placeholderResolution: 'संक्षेप में समाधान बताएं…',
    btnUpdateStatus: 'स्थिति अपडेट करें',
    sectionComments: 'टिप्पणियाँ',
    sectionCommentsCount: 'टिप्पणियाँ ({{count}})',
    noComments: 'अभी कोई टिप्पणी नहीं। नीचे बातचीत शुरू करें।',
    composerClosed: 'यह शिकायत बंद है',
    composerReply: 'किरायेदार को जवाब दें…',
    statusInProgress: 'जारी',
    statusResolved: 'हल हुई',
    statusRejected: 'अस्वीकृत',
  },
  expenses: {
    title: 'खर्चे',
    add: 'जोड़ें',
    addBtn: 'खर्च जोड़ें',
    headerSub: "{{month}} इस माह का शुद्ध लाभ",
    allProperties: 'सभी प्रॉपर्टी',
    netProfit: 'शुद्ध लाभ',
    rentCollected: 'संग्रहित किराया',
    totalExpenses: 'कुल खर्चे',
    expenseCount: 'खर्चों की संख्या',
    sectionRecurring: 'आवर्ती मासिक',
    emptyRecurring: 'कोई आवर्ती खर्चा सेट नहीं।',
    sectionExpenses: 'खर्चे',
    emptyForMonth: '{{month}} के लिए कोई खर्चा नहीं।',
    emptyTapAdd: 'दर्ज करने के लिए जोड़ें दबाएं।',
    btnLogged: 'दर्ज हो गया',
    btnLogMonth: 'इस माह दर्ज करें',
    tagMonthly: 'मासिक',
    addExpenseTitle: 'खर्च जोड़ें',
    editExpenseTitle: 'खर्च संपादित करें',
    fieldProperty: 'प्रॉपर्टी *',
    placeholderProperty: 'प्रॉपर्टी चुनें…',
    selectPropertyTitle: 'प्रॉपर्टी चुनें',
    fieldCategory: 'श्रेणी *',
    fieldTitle: 'शीर्षक',
    placeholderTitle: 'जैसे: पानी की मोटर मरम्मत',
    fieldAmount: 'राशि *',
    placeholderAmount: '0',
    fieldMonth: 'माह',
    placeholderMonth: 'YYYY-MM',
    fieldExpenseDate: 'खर्चे की तिथि',
    placeholderExpenseDate: 'YYYY-MM-DD',
    fieldNotes: 'टिप्पणियाँ',
    placeholderNotes: 'वैकल्पिक नोट…',
    recurringTitle: 'आवर्ती मासिक खर्चा',
    recurringSub: 'यह राशि हर माह स्वचालित रूप से दर्ज हो',
    btnCancel: 'रद्द करें',
    btnSaveChanges: 'बदलाव सहेजें',
    btnAddExpense: 'खर्च जोड़ें',
    catMaintenance: 'रखरखाव',
    catElectricity: 'बिजली',
    catWater: 'पानी',
    catSociety: 'सोसायटी',
    catRepairs: 'मरम्मत',
    catCleaning: 'सफ़ाई',
    catInternet: 'इंटरनेट',
    catMisc: 'अन्य',
    alertOfflineSave: 'ऑफ़लाइन सहेजा गया',
    alertOfflineSaveMsg: 'खर्चा इस डिवाइस पर सहेजा गया। ऑनलाइन होने पर स्वचालित सिंक होगा।',
    alertOfflineUpdateMsg: 'बदलाव इस डिवाइस पर सहेजे गए। ऑनलाइन होने पर स्वचालित सिंक होंगे।',
    alertOfflineDeleteTitle: 'ऑफ़लाइन हटाया गया',
    alertOfflineDeleteMsg: 'खर्चा इस डिवाइस से हटाया गया। ऑनलाइन होने पर स्वचालित सिंक होगा।',
    alertOfflineRecurMsg: 'आवर्ती खर्चा इस डिवाइस पर सहेजा गया। ऑनलाइन होने पर सिंक होगा।',
    alertOfflineRecurLogMsg: 'इस माह का आवर्ती खर्चा इस डिवाइस पर जोड़ा गया। ऑनलाइन होने पर सिंक होगा।',
    alertAdded: 'जोड़ा गया',
    alertAddedMsg: 'खर्चा दर्ज किया गया।',
    alertUpdated: 'अपडेट किया गया',
    alertUpdatedMsg: 'खर्चा अपडेट किया गया।',
    alertDeleted: 'हटाया गया',
    alertDeletedMsg: 'खर्चा हटा दिया गया।',
    alertLogged: 'दर्ज किया गया',
    alertLoggedMsg: 'इस माह का आवर्ती खर्चा जोड़ा गया।',
    errAdd: 'खर्चा जोड़ने में विफल।',
    errUpdate: 'खर्चा अपडेट करने में विफल।',
    errDelete: 'खर्चा हटाने में विफल।',
    errLogRecur: 'आवर्ती खर्चा दर्ज करने में विफल।',
    deleteTitle: 'खर्चा मिटाएं',
    deleteMsg: '"{{title}}" ({{amount}}) हटाएं?',
    btnDelete: 'मिटाएं',
    missingPropTitle: 'प्रॉपर्टी गायब',
    missingPropMsg: 'इस आवर्ती खर्चे की कोई प्रॉपर्टी नहीं। कृपया मैन्युअल जोड़ें।',
    alreadyLoggedTitle: 'पहले से दर्ज',
    alreadyLoggedMsg: 'यह आवर्ती खर्चा {{month}} के लिए पहले से दर्ज है।',
    expenseFallback: 'खर्चा',
    recurringFallback: 'आवर्ती खर्चा',
  },
  reports: {
    title: 'रिपोर्ट',
    btnPdf: 'PDF',
    profitSummary: 'लाभ सारांश',
    rentCollected: 'संग्रहित किराया',
    expenses: 'खर्चे',
    netProfit: 'शुद्ध लाभ',
    expenseRecorded: 'इस माह {{count}} खर्चे दर्ज',
    sectionBreakdown: 'आय व खर्च विवरण',
    totalIncome: 'कुल आय',
    emptyExp: 'इस अवधि के लिए कोई खर्चा दर्ज नहीं।',
    recurringSuffix: ' · आवर्ती',
    errExport: 'रिपोर्ट निर्यात नहीं हो सकी। फिर कोशिश करें।',
  },
  profile: {
    title: 'प्रोफ़ाइल',
    sub: 'भुगतान व खाता विवरण मैनेज करें',
    roleBadge: 'मालिक',
    sectionQr: 'भुगतान QR कोड',
    qrSub: 'किरायेदार इस QR को स्कैन कर आपको किराया देते हैं।',
    qrPlaceholder: 'अभी कोई QR अपलोड नहीं',
    btnUploadQr: 'QR अपलोड / बदलें',
    sectionUpi: 'UPI भुगतान विवरण',
    fieldUpiId: 'UPI आईडी',
    fieldUpiName: 'पंजीकृत नाम',
    fieldUpiNumber: 'UPI नंबर',
    btnSaveUpi: 'UPI विवरण सहेजें',
    sectionBank: 'बैंक विवरण',
    bankSub: 'निकासी और किराया भुगतान के लिए।',
    fieldAccountHolder: 'खाता धारक',
    fieldAccountNumber: 'खाता नंबर',
    fieldBankName: 'बैंक का नाम',
    fieldIfsc: 'IFSC कोड',
    btnSaveBank: 'बैंक विवरण सहेजें',
    sectionAccount: 'खाता',
    btnSignOut: 'साइन आउट',
    alertSavedTitle: 'सहेजा गया',
    alertSavedUpiMsg: 'UPI भुगतान विवरण अपडेट किया गया।',
    alertSavedBankMsg: 'बैंक विवरण अपडेट किया गया।',
    alertQrTitle: 'हो गया',
    alertQrMsg: 'भुगतान QR कोड अपडेट किया गया। किरायेदार अब इस QR को स्कैन कर भुगतान कर सकते हैं।',
    alertErrUpi: 'UPI विवरण सहेजने में विफल।',
    alertErrBank: 'बैंक विवरण सहेजने में विफल।',
    alertErrQr: 'QR कोड अपलोड करने में विफल।',
    alertPermissionTitle: 'अनुमति',
    alertPermissionMsg: 'गैलरी अनुमति आवश्यक है।',
  },
  placeholder: {
    comingSoon: 'यह स्क्रीन जल्द आ रही है।',
  },
};

// ─── Apply to each target ──────────────────────────────────────────────────
function loadFile(lang) {
  const fp = path.join(__dirname, 'src', 'localization', 'translations', `${lang}.json`);
  let raw = fs.readFileSync(fp, 'utf8');
  let bom = false;
  if (raw.charCodeAt(0) === 0xFEFF) { bom = true; raw = raw.slice(1); }
  const data = JSON.parse(raw);
  return { fp, bom, data };
}

function deepMergeInto(target, source) {
  for (const key of Object.keys(source)) {
    const tv = target[key];
    const sv = source[key];
    const tvIsObj = tv !== null && typeof tv === 'object' && !Array.isArray(tv);
    const svIsObj = sv !== null && typeof sv === 'object' && !Array.isArray(sv);
    if (svIsObj && tvIsObj) {
      deepMergeInto(tv, sv);
    } else if (!(key in target) || (svIsObj && !tvIsObj)) {
      target[key] = sv;
    }
  }
  return target;
}

const HI_DATA = HI;
const { fp, bom, data } = loadFile('hi');
if (!data.owner) data.owner = {};
deepMergeInto(data.owner, HI_DATA);
const out = JSON.stringify(data, null, 2) + '\n';
fs.writeFileSync(fp, (bom ? '﻿' : '') + out, 'utf8');
console.log('✓ hi:', Object.keys(data.owner).filter(k => typeof data.owner[k] === 'object').length, 'nested keys');
