// One-shot script: injects all owner portal keys (English) into en.json
// Safe to re-run (only adds keys; existing keys preserved).
const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, 'src', 'localization', 'translations', 'en.json');

let raw = fs.readFileSync(FILE, 'utf8');
let hasBom = false;
if (raw.charCodeAt(0) === 0xFEFF) {
  hasBom = true;
  raw = raw.slice(1);
}
const data = JSON.parse(raw);

// ===== Define all new owner portal keys (English source) =====
const newKeys = {
  // Common owner terms (used across multiple screens)
  commonOwner: {
    saveChanges: 'Save Changes',
    remove: 'Remove',
    cancel: 'Cancel',
    error: 'Error',
    verified: 'Verified',
    rejected: 'Rejected',
    property: 'Property',
    floor: 'Floor',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    yes: 'Yes',
    no: 'No',
    notes: 'Notes',
    room: 'Room',
    months: 'Months',
  },

  // Drawer menu items (owner-specific)
  drawer: {
    ownerDashboard: 'Dashboard',
    ownerProperties: 'Properties',
    ownerTenants: 'Tenants',
    ownerAddTenant: 'Add Tenant',
    ownerPayments: 'Payments',
    ownerApprovals: 'Pending Approvals',
    ownerComplaints: 'Complaints',
    ownerExpenses: 'Expenses',
    ownerReports: 'Reports',
    ownerNotifications: 'Notifications',
    helpCenter: 'Help Center',
    about: 'About Happy Renting',
    visitWebsite: 'Visit Website',
    rateApp: 'Rate the App',
    shareApp: 'Share Happy Renting',
    shareMessage: 'Manage rent, pay bills, and track your property hassle-free with Happy Renting! Download the app: https://play.google.com/store/apps/details?id=co.in.happyrenting.tenant',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    logout: 'Logout',
    logoutConfirmTitle: 'Logout',
    logoutConfirmMsg: 'Are you sure you want to logout?',
    shareErrorMsg: 'Could not share the app link. Please try again.',
    ownerWorkspace: 'Owner Workspace',
    tenantWorkspace: 'Tenant Workspace',
  },

  // ─── Dashboard ────────────────────────────────────────────────────────────
  dashboard: {
    title: 'Dashboard',
    welcome: 'Welcome back, {{name}}',
    totalCollected: 'Total Collected',
    today: 'Today',
    overdue: 'Overdue',
    outstanding: 'Outstanding',
    netCollectionMonth: 'Net Collection (this month)',
    collected: 'Collected',
    expenses: 'Expenses',
    entries: 'Entries',
    overview: 'Overview',
    properties: 'Properties',
    rooms: 'Rooms',
    activeTenants: 'Active Tenants',
    occupancy: 'Occupancy',
    paidBills: 'Paid Bills',
    overdueBills: 'Overdue Bills',
    paymentBreakdown: 'Payment Breakdown',
    pendingBills: 'Pending bills',
    partialPayments: 'Partial payments',
    overdueBillsBreakdown: 'Overdue bills',
    totalOutstanding: 'Total outstanding',
    seeAll: 'See all',
    loadError: 'Could not load stats. Pull down to retry.',
  },

  // ─── Properties ──────────────────────────────────────────────────────────
  properties: {
    title: 'Properties',
    count_one: '{{count}} property',
    count_other: '{{count}} properties',
    add: 'Add',
    addBtn: 'Add Property',
    addTitle: 'Add Property',
    editTitle: 'Edit Property',
    fieldName: 'Property Name *',
    fieldAddress: 'Address *',
    fieldCity: 'City',
    placeholderName: 'e.g. Green Valley Apartments',
    placeholderAddress: 'Street, area, landmark…',
    placeholderCity: 'e.g. Chennai',
    cancel: 'Cancel',
    save: 'Save Changes',
    saveAdd: 'Add Property',
    removeTitle: 'Remove Property',
    removeMsg: 'Remove "{{name}}"? This will deactivate the property. Tenant and room data will be preserved.',
    errCreate: 'Failed to create property.',
    errUpdate: 'Failed to update property.',
    errRemove: 'Failed to remove property.',
    loading: 'Loading properties…',
    emptyTitle: 'No properties yet',
    emptyBody: 'Tap the Add button to create your first property.',
    statsTotal: 'Total',
    statsOccupied: 'Occupied',
    statsVacant: 'Vacant',
    statsOccupancy: 'Occupancy',
    noRooms: 'No rooms yet. Tap the card to add rooms.',
  },

  // ─── Rooms ──────────────────────────────────────────────────────────────
  rooms: {
    title: 'Rooms',
    add: 'Add',
    addBtn: 'Add Room',
    addTitle: 'Add Room',
    editTitle: 'Edit Room',
    fieldRoomNumber: 'Room Number *',
    fieldFloor: 'Floor',
    fieldCapacity: 'Capacity *',
    fieldMonthlyRent: 'Monthly Rent (₹)',
    fieldSecurityDeposit: 'Security Deposit (₹)',
    fieldDescription: 'Description',
    placeholderRoomNumber: 'e.g. 101',
    placeholderFloor: 'e.g. Ground',
    placeholderDescription: 'Optional notes',
    infoOccupied: 'Occupied {{occupied}}/{{capacity}} · capacity cannot be lowered below occupancy',
    errCapacityMin: 'Capacity must be at least {{min}}',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    saveAdd: 'Add Room',
    removeTitle: 'Remove Room',
    removeMsg: 'Remove Room {{number}}? This cannot be undone if the room is not occupied.',
    errCreate: 'Failed to create room.',
    errUpdate: 'Failed to update room.',
    errRemove: 'Failed to remove room.',
    emptyTitle: 'No rooms yet',
    emptySub: 'Tap Add to create your first room.',
    propertyFallback: 'Property',
    count_one: '{{count}} room',
    count_other: '{{count}} rooms',
    floorPrefix: '· Floor {{floor}}',
    rent: 'Rent {{amount}}',
    deposit: 'Deposit {{amount}}',
    badgeFull: 'Full',
    badgeAvailable: 'Available',
    occupiedCount: '{{occupied}}/{{capacity}} occupied',
  },

  // ─── Tenants list ───────────────────────────────────────────────────────
  tenants: {
    title: 'Tenants',
    add: 'Add',
    addBtn: 'Add Tenant',
    count_one: '{{count}} total',
    count_other: '{{count}} total',
    countActive_one: '{{count}} active',
    countActive_other: '{{count}} active',
    countVacated_one: '{{count}} vacated',
    countVacated_other: '{{count}} vacated',
    tabActive: 'Active',
    tabVacated: 'Vacated',
    tabAll: 'All',
    searchPlaceholder: 'Search by name, room, property…',
    emptyNoSearch: 'No results found',
    emptyNoTenants: 'No tenants',
    emptyNoActive: 'No active tenants',
    emptyNoVacated: 'No vacated tenants',
    // Detail sheet
    detailRoom: 'Room',
    detailProperty: 'Property',
    detailMonthlyRent: 'Monthly Rent',
    detailMoveIn: 'Move-in Date',
    detailExit: 'Exit Date',
    detailPhone: 'Phone',
    detailIdNumber: 'ID Number',
    detailSecurityDeposit: 'Security Deposit',
    detailAdvancePaid: 'Advance Paid',
    detailNotes: 'Notes',
    detailEdit: 'Edit Details',
    detailMoveOut: 'Move Out Tenant',
    detailReverse: 'Reverse Move-Out',
    refundDue: 'Refund Due',
    refundSettled: 'Refund Settled',
    markSettled: 'Mark Settled',
    // Status badges
    statusActive: 'Active',
    statusVacated: 'Vacated',
    statusPendingDeletion: 'Pending Deletion',
    // Card
    since: 'Since {{date}}',
    // Move-out modal
    moveOutTitle: 'Move Out Tenant',
    moveOutFieldExitDate: 'Exit Date *',
    moveOutFieldNotes: 'Notes (optional)',
    moveOutPlaceholderNotes: 'Reason for move-out…',
    moveOutConfirm: 'Confirm Move Out',
    moveOutAlertTitle: 'Done',
    moveOutAlertMsg: 'Tenant has been moved out successfully.',
    moveOutErr: 'Move-out failed. Please try again.',
    moveOutEmptyExitDate: 'Exit Date',
    // Reverse move-out
    reverseAlertTitle: 'Reverse Move-Out',
    reverseAlertMsg: 'Restore {{name}} (Room {{room}}) back to active? This will re-occupy the room.',
    reverseAlertRestore: 'Restore',
    reverseDeletedTitle: 'Cannot Reverse Move-Out',
    reverseDeletedMsg: "This tenant's account has been deleted. Move-out cannot be reversed.",
    reverseOk: 'OK',
    reverseDoneTitle: 'Reversed',
    reverseDoneMsg: 'Tenant has been restored to active status.',
    reverseErr: 'Reversal failed. Please try again.',
    // Edit tenant modal
    editTitle: 'Edit Tenant',
    editTabFinance: 'Finance',
    editTabProfile: 'Profile',
    editErrAdvanceDeposit: 'Advance paid should be less than or equal to the security deposit.',
    editFieldTargetDeposit: 'Target Security Deposit (Total ₹)',
    editFieldPaid: 'Currently Paid (₹)',
    editFieldFullName: 'Full Name',
    editFieldEmail: 'Email',
    editFieldPhone: 'Phone',
    editFieldIdNumber: 'ID Number',
    editPlaceholderDeposit: 'Total amount expected to pay',
    editHintDeposit: 'Total amount the tenant is expected to pay.',
    editPlaceholderPaid: '0',
    editPlaceholderName: 'Tenant full name',
    editPlaceholderEmail: 'tenant@example.com',
    editPlaceholderPhone: 'Tenant phone',
    editPlaceholderId: 'Aadhaar / Govt ID number',
    editSavedTitle: 'Saved',
    editSavedMsg: 'Tenant details updated successfully.',
    editErr: 'Update failed. Please try again.',
    // Refund settle
    refundTitle: 'Mark Refund Settled',
    refundFieldNote: 'Note (optional)',
    refundPlaceholderNote: 'Optional note for this refund…',
    refundConfirm: 'Mark Settled',
    refundAlertTitle: 'Settled',
    refundAlertMsg: 'Refund marked as settled.',
    refundErr: 'Failed to settle refund. Please try again.',
  },

  // ─── Add Tenant ─────────────────────────────────────────────────────────
  addTenant: {
    title: 'Add Tenant',
    sub: 'Move a tenant into a room',
    sectionRoom: '1. Assign Room',
    sectionTenant: '2. Tenant',
    sectionDetails: '3. Lease Details',
    selectRoomPlaceholder: 'Select a vacant room…',
    errRoomFull: 'This room is full.',
    segmentExisting: 'Existing User',
    segmentNew: 'Create New',
    selectUserPlaceholder: 'Select a registered user…',
    labelFullName: 'Full Name *',
    labelEmail: 'Email *',
    placeholderName: 'Tenant name',
    placeholderEmail: 'tenant@email.com',
    btnSendOtp: 'Send OTP',
    labelOtp: 'OTP',
    placeholderOtp: '6-digit',
    btnVerify: 'Verify',
    verified: 'Email verified',
    labelPassword: 'Temporary Password *',
    placeholderPassword: 'Set a password',
    passwordHint: 'Min 8 chars with uppercase, lowercase, number & special character (@$!%*?&)',
    btnAccountCreated: 'Account created',
    btnCreateAccount: 'Create Account',
    labelPhone: 'Phone *',
    placeholderPhone: 'Tenant phone',
    labelIdNumber: 'ID Number',
    placeholderIdNumber: 'Aadhaar / Govt ID number',
    labelJoinDate: 'Join Date *',
    placeholderJoinDate: 'Select date…',
    labelSecurityDeposit: 'Security Deposit (₹)',
    labelAdvancePaid: 'Advance Paid (₹)',
    labelNotes: 'Notes',
    placeholderNotes: 'Optional notes',
    btnSubmit: 'Add Tenant',
    alertRegisterTitle: 'Register failed',
    alertRegisterMsg: 'Failed to create account.',
    alertMissingTitle: 'Missing details',
    alertMissingName: 'Please enter the tenant name.',
    alertInvalidNameTitle: 'Invalid name',
    alertInvalidNameMsg: 'Name must be at least 2 characters.',
    alertWeakPwTitle: 'Weak password',
    alertWeakPwMin: 'Password must be at least 8 characters.',
    alertWeakPwChars: 'Password must contain uppercase, lowercase, number, and special character (@$!%*?&).',
    alertDone: 'Done',
    alertDoneMsg: 'Tenant has been moved in successfully.',
    alertErr: 'Failed to add tenant.',
    selectRoomTitle: 'Select Room',
    selectUserTitle: 'Select User',
    userAlreadyActive: 'Already an active tenant',
    selectDateTitle: 'Select Join Date',
    occupancySuffix: '{{occupied}}/{{capacity}} occupied',
    rentPerMonth: '{{amount}}/mo',
  },

  // ─── Payments ───────────────────────────────────────────────────────────
  payments: {
    title: 'Payments',
    headerSub: 'Collected ₹{{amount}} today',
    stripOverdue: 'Overdue',
    stripPending: 'Pending',
    stripCollected: 'Collected',
    tabAll: 'All',
    tabOverdue: 'Overdue',
    tabPending: 'Pending',
    tabPartial: 'Partial',
    tabPaid: 'Paid',
    searchPlaceholder: 'Search by tenant, room, month…',
    emptyNoSearch: 'No results found',
    emptyNoRecords: 'No {{status}} records',
    statusPending: 'Pending',
    statusPartial: 'Partial',
    statusOverdue: 'Overdue',
    statusPaid: 'Paid',
    amountTotal: 'Total',
    amountPaid: 'Paid',
    amountRemaining: 'Remaining',
    proofAwaiting: 'Payment proof awaiting verification',
    btnVerify: 'Verify',
    btnReject: 'Reject',
    verifyAlertTitle: 'Verify Payment',
    verifyAlertMsg: 'Confirm this payment proof and credit it to the tenant?',
    verifyAlertConfirm: 'Verify',
    verifiedAlertTitle: 'Verified',
    verifiedAlertMsg: 'Payment has been verified and credited.',
    rejectedAlertTitle: 'Rejected',
    rejectedAlertMsg: 'Payment proof has been rejected. Tenant will be notified.',
    errVerify: 'Verification failed.',
    errReject: 'Rejection failed.',
    rejectModalTitle: 'Reject Payment',
    rejectModalSub: 'Provide a reason so the tenant knows why their proof was rejected.',
    rejectPlaceholder: 'e.g. Blurry image, wrong amount…',
    btnCancel: 'Cancel',
  },

  // ─── Approvals ──────────────────────────────────────────────────────────
  approvals: {
    title: 'Pending Approvals',
    count_one: '{{count}} awaiting verification',
    count_other: '{{count}} awaiting verifications',
    allCaughtTitle: 'All caught up!',
    allCaughtSub: 'No payment proofs waiting for approval.',
    btnApprove: 'Approve',
    btnReject: 'Reject',
    rejectTitle: 'Reject Payment',
    rejectSub: 'Provide a reason so the tenant knows why their proof was rejected.',
    rejectPlaceholder: 'e.g. Wrong amount, blurry image…',
    btnCancel: 'Cancel',
    errVerify: 'Verification failed.',
    errReject: 'Rejection failed.',
  },

  // ─── Transaction Detail ─────────────────────────────────────────────────
  transactions: {
    fallbackTitle: 'Payment',
    totalCollected: 'Total Collected',
    floatBanner: 'Floating balance: {{amount}} is carried forward',
    proofAwaiting: 'Payment proof awaiting verification',
    sectionTransactions: 'Transactions',
    emptyTitle: 'No transactions recorded yet.',
    btnRecordPayment: 'Record Payment',
    addPaymentTitle: 'Record Payment',
    fieldAmount: 'Amount (₹) *',
    fieldMethod: 'Payment Method *',
    methodCash: 'Cash',
    methodUpi: 'UPI',
    methodBank: 'Bank',
    methodCheque: 'Cheque',
    fieldDate: 'Payment Date *',
    placeholderDate: 'YYYY-MM-DD',
    fieldNotes: 'Notes',
    placeholderNotes: 'Optional reference',
    btnAttachProof: 'Attach payment proof (optional)',
    btnCancel: 'Cancel',
    btnRecord: 'Record Payment',
    btnVerify: 'Verify',
    btnReject: 'Reject',
    btnReverse: 'Reverse this payment',
    btnUndoReversal: 'Undo Reversal',
    refLabel: 'Ref: {{ref}}',
    recordedBy: 'Recorded by {{name}} ({{role}})',
    alertPermissionTitle: 'Permission',
    alertPermissionMsg: 'Gallery permission is required to attach proof.',
    alertErrRecord: 'Failed to record payment.',
    errVerify: 'Verification failed.',
    errReject: 'Rejection failed.',
    errReverse: 'Reversal failed.',
    errUndo: 'Failed to undo reversal.',
    errLoad: 'Could not load payment details',
    btnRetry: 'Retry',
    reversedAlertTitle: 'Reversed',
    reversedAlertMsg: 'Payment has been reversed.',
    undoneAlertTitle: 'Undone',
    undoneAlertMsg: 'Reversal undone. Payment re-applied to the rent record.',
    undoTitle: 'Undo Reversal',
    undoMsg: 'Re-apply {{amount}} back to this rent record?',
    undoConfirm: 'Undo',
    reverseTitle: 'Reverse Payment',
    reverseSub: '{{amount}} recorded on {{date}}',
    reversePlaceholder: 'Reason for reversal (required)',
    reverseBtn: 'Reverse',
    btnCancel2: 'Cancel',
    statusCompleted: 'Completed',
    statusVerifying: 'Verifying',
    statusReversed: 'Reversed',
    statusFailed: 'Failed',
    floatMovedOut: 'Floating amount −{{amount}} moved out of this month',
    floatMovedIn: 'Floating amount +{{amount}} carried into this month',
  },

  // ─── Complaints ─────────────────────────────────────────────────────────
  complaints: {
    title: 'Complaints',
    count_one: '{{count}} complaint',
    count_other: '{{count}} complaints',
    tabAll: 'All',
    tabOpen: 'Open',
    tabInProgress: 'In Progress',
    tabResolved: 'Resolved',
    searchPlaceholder: 'Search by title or tenant…',
    emptyNoSearch: 'No results found',
    emptyDefault: 'No complaints here',
    statusOpen: 'Open',
    statusInProgress: 'In Progress',
    statusResolved: 'Resolved',
    statusRejected: 'Rejected',
    statusClosed: 'Closed',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    noLocation: 'No location',
  },

  // ─── Complaint Detail ───────────────────────────────────────────────────
  complaintDetail: {
    title: 'Complaint',
    errLoad: 'Could not load complaint',
    btnRetry: 'Retry',
    badgePrioritySuffix: '{{label}} priority',
    resolutionNotes: 'Resolution Notes',
    sectionUpdateStatus: 'Update Status',
    fieldResolutionNotes: 'Resolution Notes *',
    placeholderResolution: 'Briefly describe the resolution…',
    btnUpdateStatus: 'Update Status',
    sectionComments: 'Comments',
    sectionCommentsCount: 'Comments ({{count}})',
    noComments: 'No comments yet. Start a conversation below.',
    composerClosed: 'This complaint is closed',
    composerReply: 'Reply to the tenant…',
    statusInProgress: 'In Progress',
    statusResolved: 'Resolved',
    statusRejected: 'Rejected',
  },

  // ─── Expenses ───────────────────────────────────────────────────────────
  expenses: {
    title: 'Expenses',
    add: 'Add',
    addBtn: 'Add Expense',
    headerSub: "{{month}} this month's net profit",
    allProperties: 'All properties',
    netProfit: 'Net Profit',
    rentCollected: 'Rent Collected',
    totalExpenses: 'Total Expenses',
    expenseCount: 'Expense Count',
    sectionRecurring: 'Recurring Monthly',
    emptyRecurring: 'No recurring expenses set up.',
    sectionExpenses: 'Expenses',
    emptyForMonth: 'No expenses for {{month}}.',
    emptyTapAdd: 'Tap Add to record one.',
    btnLogged: 'Logged',
    btnLogMonth: 'Log this month',
    tagMonthly: 'Monthly',
    // Form modal
    addExpenseTitle: 'Add Expense',
    editExpenseTitle: 'Edit Expense',
    fieldProperty: 'Property *',
    placeholderProperty: 'Select property…',
    selectPropertyTitle: 'Select Property',
    fieldCategory: 'Category *',
    fieldTitle: 'Title',
    placeholderTitle: 'e.g. Water pump fix',
    fieldAmount: 'Amount *',
    placeholderAmount: '0',
    fieldMonth: 'Month',
    placeholderMonth: 'YYYY-MM',
    fieldExpenseDate: 'Expense Date',
    placeholderExpenseDate: 'YYYY-MM-DD',
    fieldNotes: 'Notes',
    placeholderNotes: 'Optional note…',
    recurringTitle: 'Recurring monthly expense',
    recurringSub: 'Log this amount automatically every month',
    btnCancel: 'Cancel',
    btnSaveChanges: 'Save Changes',
    btnAddExpense: 'Add Expense',
    // Category labels
    catMaintenance: 'Maintenance',
    catElectricity: 'Electricity',
    catWater: 'Water',
    catSociety: 'Society',
    catRepairs: 'Repairs',
    catCleaning: 'Cleaning',
    catInternet: 'Internet',
    catMisc: 'Misc',
    // Alerts
    alertOfflineSave: 'Saved offline',
    alertOfflineSaveMsg: 'Expense saved on this device. It will sync automatically when back online.',
    alertOfflineUpdateMsg: 'Changes saved on this device. They will sync automatically when back online.',
    alertOfflineDeleteTitle: 'Deleted offline',
    alertOfflineDeleteMsg: 'Expense removed on this device. It will sync automatically when back online.',
    alertOfflineRecurMsg: 'Recurring expense saved on this device. It will sync when back online.',
    alertOfflineRecurLogMsg: 'Recurring expense added for this month on this device. It will sync when back online.',
    alertAdded: 'Added',
    alertAddedMsg: 'Expense has been recorded.',
    alertUpdated: 'Updated',
    alertUpdatedMsg: 'Expense has been updated.',
    alertDeleted: 'Deleted',
    alertDeletedMsg: 'Expense has been removed.',
    alertLogged: 'Logged',
    alertLoggedMsg: 'Recurring expense added for this month.',
    errAdd: 'Failed to add expense.',
    errUpdate: 'Failed to update expense.',
    errDelete: 'Failed to delete expense.',
    errLogRecur: 'Failed to log recurring expense.',
    deleteTitle: 'Delete Expense',
    deleteMsg: 'Remove "{{title}}" ({{amount}})?',
    btnDelete: 'Delete',
    missingPropTitle: 'Missing Property',
    missingPropMsg: 'This recurring expense has no property. Please add it manually.',
    alreadyLoggedTitle: 'Already logged',
    alreadyLoggedMsg: 'This recurring expense is already logged for {{month}}.',
    expenseFallback: 'Expense',
    recurringFallback: 'Recurring expense',
  },

  // ─── Reports ────────────────────────────────────────────────────────────
  reports: {
    title: 'Reports',
    btnPdf: 'PDF',
    profitSummary: 'Profit Summary',
    rentCollected: 'Rent Collected',
    expenses: 'Expenses',
    netProfit: 'Net Profit',
    expenseRecorded: '{{count}} expenses recorded this month',
    sectionBreakdown: 'Income & Expense Breakdown',
    totalIncome: 'Total Income',
    emptyExp: 'No expenses recorded for this period.',
    recurringSuffix: ' · recurring',
    errExport: 'Could not export report. Try again.',
  },

  // ─── Profile ────────────────────────────────────────────────────────────
  profile: {
    title: 'Profile',
    sub: 'Manage payment & account details',
    roleBadge: 'Owner',
    sectionQr: 'Payment QR Code',
    qrSub: 'Tenants scan this QR to pay rent to you.',
    qrPlaceholder: 'No QR uploaded yet',
    btnUploadQr: 'Upload / Replace QR',
    sectionUpi: 'UPI Payment Details',
    fieldUpiId: 'UPI ID',
    fieldUpiName: 'Registered Name',
    fieldUpiNumber: 'UPI Number',
    btnSaveUpi: 'Save UPI Details',
    sectionBank: 'Bank Details',
    bankSub: 'Used for withdrawals and rent payouts.',
    fieldAccountHolder: 'Account Holder',
    fieldAccountNumber: 'Account Number',
    fieldBankName: 'Bank Name',
    fieldIfsc: 'IFSC Code',
    btnSaveBank: 'Save Bank Details',
    sectionAccount: 'Account',
    btnSignOut: 'Sign Out',
    alertSavedTitle: 'Saved',
    alertSavedUpiMsg: 'UPI payment details updated.',
    alertSavedBankMsg: 'Bank details updated.',
    alertQrTitle: 'Done',
    alertQrMsg: 'Payment QR code updated. Tenants can now scan this QR to pay rent.',
    alertErrUpi: 'Failed to save UPI details.',
    alertErrBank: 'Failed to save bank details.',
    alertErrQr: 'Failed to upload QR code.',
    alertPermissionTitle: 'Permission',
    alertPermissionMsg: 'Gallery permission is required.',
  },

  // ─── Placeholder ────────────────────────────────────────────────────────
  placeholder: {
    comingSoon: 'This screen is coming soon.',
  },
};

// Deep merge helper - target must be an object for nested merge to work.
function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    const tv = target[key];
    const sv = source[key];
    const tvIsObj = tv !== null && typeof tv === 'object' && !Array.isArray(tv);
    const svIsObj = sv !== null && typeof sv === 'object' && !Array.isArray(sv);
    if (svIsObj && tvIsObj) {
      deepMerge(tv, sv);
    } else if (!(key in target) || (svIsObj && !tvIsObj)) {
      // Replace scalar existing value with incoming object (needed for nested namespaces
      // that collide with previously flat keys like "owner.dashboard" = "Dashboard").
      target[key] = sv;
    }
  }
  return target;
}

deepMerge(data.owner, newKeys);

const out = JSON.stringify(data, null, 2) + '\n';
const finalOut = (hasBom ? '﻿' : '') + out;
fs.writeFileSync(FILE, finalOut, 'utf8');
console.log('✓ Wrote', FILE);
console.log('  Total owner.* keys:', Object.keys(data.owner).length);
