// One-shot script: adds Kannada translations for all owner portal keys.
const fs = require('fs');
const path = require('path');

const KN = {
  commonOwner: {
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    remove: 'ತೆಗೆದುಹಾಕಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    error: 'ದೋಷ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    property: 'ಆಸ್ತಿ',
    floor: 'ಮಹಡಿ',
    add: 'ಸೇರಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    notes: 'ಟಿಪ್ಪಣಿಗಳು',
    room: 'ಕೋಣೆ',
    months: 'ತಿಂಗಳುಗಳು',
  },
  drawer: {
    ownerDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    ownerProperties: 'ಆಸ್ತಿಗಳು',
    ownerTenants: 'ಬಾಡಿಗೆದಾರರು',
    ownerAddTenant: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸೇರಿಸಿ',
    ownerPayments: 'ಪಾವತಿಗಳು',
    ownerApprovals: 'ಬಾಕಿ ಅನುಮೋದನೆಗಳು',
    ownerComplaints: 'ದೂರುಗಳು',
    ownerExpenses: 'ಖರ್ಚುಗಳು',
    ownerReports: 'ವರದಿಗಳು',
    ownerNotifications: 'ಸೂಚನೆಗಳು',
    helpCenter: 'ಸಹಾಯ ಕೇಂದ್ರ',
    about: 'Happy Renting ಬಗ್ಗೆ',
    visitWebsite: 'ವೆಬ್‌ಸೈಟ್ ನೋಡಿ',
    rateApp: 'ಆ್ಯಪ್ ಅನ್ನು ರೇಟ್ ಮಾಡಿ',
    shareApp: 'Happy Renting ಹಂಚಿಕೊಳ್ಳಿ',
    shareMessage: 'Happy Renting ನೊಂದಿಗೆ ಬಾಡಿಗೆ, ಬಿಲ್ ಮತ್ತು ನಿಮ್ಮ ಆಸ್ತಿಯನ್ನು ಸುಲಭವಾಗಿ ನಿರ್ವಹಿಸಿ! ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ: https://play.google.com/store/apps/details?id=co.in.happyrenting.tenant',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    logoutConfirmTitle: 'ಲಾಗ್ ಔಟ್',
    logoutConfirmMsg: 'ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಆಗಲು ಬಯಸುತ್ತೀರಾ?',
    shareErrorMsg: 'ಆ್ಯಪ್ ಲಿಂಕ್ ಹಂಚಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    ownerWorkspace: 'ಮಾಲೀಕರ ಕಾರ್ಯಕ್ಷೇತ್ರ',
    tenantWorkspace: 'ಬಾಡಿಗೆದಾರರ ಕಾರ್ಯಕ್ಷೇತ್ರ',
  },
  dashboard: {
    title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ, {{name}}',
    totalCollected: 'ಒಟ್ಟು ಸಂಗ್ರಹ',
    today: 'ಇಂದು',
    overdue: 'ಮಿತಿಮೀರಿದೆ',
    outstanding: 'ಬಾಕಿ',
    netCollectionMonth: 'ನಿವ್ವಳ ಸಂಗ್ರಹ (ಈ ತಿಂಗಳು)',
    collected: 'ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
    expenses: 'ಖರ್ಚುಗಳು',
    entries: 'ನಮೂದುಗಳು',
    overview: 'ಅವಲೋಕನ',
    properties: 'ಆಸ್ತಿಗಳು',
    rooms: 'ಕೋಣೆಗಳು',
    activeTenants: 'ಸಕ್ರಿಯ ಬಾಡಿಗೆದಾರರು',
    occupancy: 'ಆಕ್ರಮಣೆ',
    paidBills: 'ಪಾವತಿಸಿದ ಬಿಲ್‌ಗಳು',
    overdueBills: 'ಮಿತಿಮೀರಿದ ಬಿಲ್‌ಗಳು',
    paymentBreakdown: 'ಪಾವತಿ ವಿವರ',
    pendingBills: 'ಬಾಕಿ ಬಿಲ್‌ಗಳು',
    partialPayments: 'ಭಾಗಶಃ ಪಾವತಿಗಳು',
    overdueBillsBreakdown: 'ಮಿತಿಮೀರಿದ ಬಿಲ್‌ಗಳು',
    totalOutstanding: 'ಒಟ್ಟು ಬಾಕಿ',
    seeAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    loadError: 'ಅಂಕಿಅಂಶಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ಕೆಳಗೆ ಎಳೆಯಿರಿ.',
  },
  properties: {
    title: 'ಆಸ್ತಿಗಳು',
    count_one: '{{count}} ಆಸ್ತಿ',
    count_other: '{{count}} ಆಸ್ತಿಗಳು',
    add: 'ಸೇರಿಸಿ',
    addBtn: 'ಆಸ್ತಿ ಸೇರಿಸಿ',
    addTitle: 'ಆಸ್ತಿ ಸೇರಿಸಿ',
    editTitle: 'ಆಸ್ತಿ ಸಂಪಾದಿಸಿ',
    fieldName: 'ಆಸ್ತಿಯ ಹೆಸರು *',
    fieldAddress: 'ವಿಳಾಸ *',
    fieldCity: 'ನಗರ',
    placeholderName: 'ಉದಾ: ಗ್ರೀನ್ ವ್ಯಾಲಿ ಅಪಾರ್ಟ್‌ಮೆಂಟ್',
    placeholderAddress: 'ಬೀದಿ, ಪ್ರದೇಶ, ಗುರುತು…',
    placeholderCity: 'ಉದಾ: ಚೆನ್ನೈ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    saveAdd: 'ಆಸ್ತಿ ಸೇರಿಸಿ',
    removeTitle: 'ಆಸ್ತಿ ತೆಗೆದುಹಾಕಿ',
    removeMsg: '"{{name}}" ತೆಗೆದುಹಾಕಬೇಕೆ? ಇದರಿಂದ ಆಸ್ತಿ ನಿಷ್ಕ್ರಿಯಗೊಳ್ಳುತ್ತದೆ. ಬಾಡಿಗೆದಾರರ ಮತ್ತು ಕೋಣೆಯ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ.',
    errCreate: 'ಆಸ್ತಿ ರಚಿಸಲು ವಿಫಲ.',
    errUpdate: 'ಆಸ್ತಿ ನವೀಕರಿಸಲು ವಿಫಲ.',
    errRemove: 'ಆಸ್ತಿ ತೆಗೆದುಹಾಕಲು ವಿಫಲ.',
    loading: 'ಆಸ್ತಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…',
    emptyTitle: 'ಇನ್ನೂ ಯಾವುದೇ ಆಸ್ತಿಗಳಿಲ್ಲ',
    emptyBody: 'ಮೊದಲ ಆಸ್ತಿಯನ್ನು ರಚಿಸಲು ಸೇರಿಸು ಬಟನ್ ಒತ್ತಿ.',
    statsTotal: 'ಒಟ್ಟು',
    statsOccupied: 'ಆಕ್ರಮಿತ',
    statsVacant: 'ಖಾಲಿ',
    statsOccupancy: 'ಆಕ್ರಮಣೆ',
    noRooms: 'ಇನ್ನೂ ಕೋಣೆಗಳಿಲ್ಲ. ಕೋಣೆಗಳನ್ನು ಸೇರಿಸಲು ಕಾರ್ಡ್ ಒತ್ತಿ.',
  },
  rooms: {
    title: 'ಕೋಣೆಗಳು',
    add: 'ಸೇರಿಸಿ',
    addBtn: 'ಕೋಣೆ ಸೇರಿಸಿ',
    addTitle: 'ಕೋಣೆ ಸೇರಿಸಿ',
    editTitle: 'ಕೋಣೆ ಸಂಪಾದಿಸಿ',
    fieldRoomNumber: 'ಕೋಣೆಯ ಸಂಖ್ಯೆ *',
    fieldFloor: 'ಮಹಡಿ',
    fieldCapacity: 'ಸಾಮರ್ಥ್ಯ *',
    fieldMonthlyRent: 'ಮಾಸಿಕ ಬಾಡಿಗೆ (₹)',
    fieldSecurityDeposit: 'ಭದ್ರತಾ ಠೇವಣಿ (₹)',
    fieldDescription: 'ವಿವರಣೆ',
    placeholderRoomNumber: 'ಉದಾ: 101',
    placeholderFloor: 'ಉದಾ: ನೆಲ',
    placeholderDescription: 'ಐಚ್ಛಿಕ ಟಿಪ್ಪಣಿ',
    infoOccupied: '{{occupied}}/{{capacity}} ಆಕ್ರಮಿತ · ಸಾಮರ್ಥ್ಯವನ್ನು ಆಕ್ರಮಣೆಗಿಂತ ಕಡಿಮೆ ಮಾಡಲಾಗದು',
    errCapacityMin: 'ಸಾಮರ್ಥ್ಯ ಕನಿಷ್ಠ {{min}} ಆಗಿರಬೇಕು',
    cancel: 'ರದ್ದುಮಾಡಿ',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    saveAdd: 'ಕೋಣೆ ಸೇರಿಸಿ',
    removeTitle: 'ಕೋಣೆ ತೆಗೆದುಹಾಕಿ',
    removeMsg: 'ಕೋಣೆ {{number}} ತೆಗೆದುಹಾಕಬೇಕೆ? ಕೋಣೆ ಖಾಲಿಯಾಗಿದ್ದರೆ ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗದು.',
    errCreate: 'ಕೋಣೆ ರಚಿಸಲು ವಿಫಲ.',
    errUpdate: 'ಕೋಣೆ ನವೀಕರಿಸಲು ವಿಫಲ.',
    errRemove: 'ಕೋಣೆ ತೆಗೆದುಹಾಕಲು ವಿಫಲ.',
    emptyTitle: 'ಇನ್ನೂ ಕೋಣೆಗಳಿಲ್ಲ',
    emptySub: 'ಮೊದಲ ಕೋಣೆ ರಚಿಸಲು ಸೇರಿಸು ಒತ್ತಿ.',
    propertyFallback: 'ಆಸ್ತಿ',
    count_one: '{{count}} ಕೋಣೆ',
    count_other: '{{count}} ಕೋಣೆಗಳು',
    floorPrefix: '· ಮಹಡಿ {{floor}}',
    rent: 'ಬಾಡಿಗೆ {{amount}}',
    deposit: 'ಠೇವಣಿ {{amount}}',
    badgeFull: 'ತುಂಬಿದೆ',
    badgeAvailable: 'ಲಭ್ಯ',
    occupiedCount: '{{occupied}}/{{capacity}} ಆಕ್ರಮಿತ',
  },
  tenants: {
    title: 'ಬಾಡಿಗೆದಾರರು',
    add: 'ಸೇರಿಸಿ',
    addBtn: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸೇರಿಸಿ',
    count_one: '{{count}} ಒಟ್ಟು',
    count_other: '{{count}} ಒಟ್ಟು',
    countActive_one: '{{count}} ಸಕ್ರಿಯ',
    countActive_other: '{{count}} ಸಕ್ರಿಯ',
    countVacated_one: '{{count}} ಖಾಲಿ ಮಾಡಿದವರು',
    countVacated_other: '{{count}} ಖಾಲಿ ಮಾಡಿದವರು',
    tabActive: 'ಸಕ್ರಿಯ',
    tabVacated: 'ಖಾಲಿ ಮಾಡಿದವರು',
    tabAll: 'ಎಲ್ಲಾ',
    searchPlaceholder: 'ಹೆಸರು, ಕೋಣೆ, ಆಸ್ತಿಯಿಂದ ಹುಡುಕಿ…',
    emptyNoSearch: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಸಿಗಲಿಲ್ಲ',
    emptyNoTenants: 'ಯಾವುದೇ ಬಾಡಿಗೆದಾರರಿಲ್ಲ',
    emptyNoActive: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಬಾಡಿಗೆದಾರರಿಲ್ಲ',
    emptyNoVacated: 'ಯಾವುದೇ ಖಾಲಿ ಮಾಡಿದ ಬಾಡಿಗೆದಾರರಿಲ್ಲ',
    detailRoom: 'ಕೋಣೆ',
    detailProperty: 'ಆಸ್ತಿ',
    detailMonthlyRent: 'ಮಾಸಿಕ ಬಾಡಿಗೆ',
    detailMoveIn: 'ಸೇರಿದ ದಿನಾಂಕ',
    detailExit: 'ನಿರ್ಗಮನ ದಿನಾಂಕ',
    detailPhone: 'ಫೋನ್',
    detailIdNumber: 'ಐಡಿ ಸಂಖ್ಯೆ',
    detailSecurityDeposit: 'ಭದ್ರತಾ ಠೇವಣಿ',
    detailAdvancePaid: 'ಮುಂಗಡ ಪಾವತಿ',
    detailNotes: 'ಟಿಪ್ಪಣಿಗಳು',
    detailEdit: 'ವಿವರ ಸಂಪಾದಿಸಿ',
    detailMoveOut: 'ಬಾಡಿಗೆದಾರರನ್ನು ಖಾಲಿ ಮಾಡಿ',
    detailReverse: 'ಖಾಲಿ ಮಾಡುವುದನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    refundDue: 'ರಿಫಂಡ್ ಬಾಕಿ',
    refundSettled: 'ರಿಫಂಡ್ ಪರಿಹಾರ',
    markSettled: 'ಪರಿಹಾರ ಎಂದು ಗುರುತಿಸಿ',
    statusActive: 'ಸಕ್ರಿಯ',
    statusVacated: 'ಖಾಲಿ ಮಾಡಿದರು',
    statusPendingDeletion: 'ಅಳಿಸಲು ಬಾಕಿ',
    since: '{{date}} ರಿಂದ',
    moveOutTitle: 'ಬಾಡಿಗೆದಾರರನ್ನು ಖಾಲಿ ಮಾಡಿ',
    moveOutFieldExitDate: 'ನಿರ್ಗಮನ ದಿನಾಂಕ *',
    moveOutFieldNotes: 'ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)',
    moveOutPlaceholderNotes: 'ಖಾಲಿ ಮಾಡಲು ಕಾರಣ…',
    moveOutConfirm: 'ಖಾಲಿ ಮಾಡುವುದನ್ನು ದೃಢೀಕರಿಸಿ',
    moveOutAlertTitle: 'ಆಯಿತು',
    moveOutAlertMsg: 'ಬಾಡಿಗೆದಾರರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಖಾಲಿ ಮಾಡಲಾಗಿದೆ.',
    moveOutErr: 'ಖಾಲಿ ಮಾಡಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    moveOutEmptyExitDate: 'ನಿರ್ಗಮನ ದಿನಾಂಕ',
    reverseAlertTitle: 'ಖಾಲಿ ಮಾಡುವುದನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    reverseAlertMsg: '{{name}} (ಕೋಣೆ {{room}}) ಅವರನ್ನು ಮತ್ತೆ ಸಕ್ರಿಯರನ್ನಾಗಿ ಮಾಡಬೇಕೆ? ಇದರಿಂದ ಕೋಣೆ ಮತ್ತೆ ಆಕ್ರಮಿತವಾಗುತ್ತದೆ.',
    reverseAlertRestore: 'ಮರುಸ್ಥಾಪಿಸಿ',
    reverseDeletedTitle: 'ಖಾಲಿ ಮಾಡುವುದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗದು',
    reverseDeletedMsg: 'ಈ ಬಾಡಿಗೆದಾರರ ಖಾತೆಯನ್ನು ಅಳಿಸಲಾಗಿದೆ. ಖಾಲಿ ಮಾಡುವುದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗದು.',
    reverseOk: 'ಸರಿ',
    reverseDoneTitle: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    reverseDoneMsg: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸಕ್ರಿಯ ಸ್ಥಿತಿಗೆ ಮರಳಿ ತಂದಿದೆ.',
    reverseErr: 'ರದ್ದುಗೊಳಿಸಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    editTitle: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸಂಪಾದಿಸಿ',
    editTabFinance: 'ಹಣಕಾಸು',
    editTabProfile: 'ಪ್ರೊಫೈಲ್',
    editErrAdvanceDeposit: 'ಮುಂಗಡ ಪಾವತಿಯು ಭದ್ರತಾ ಠೇವಣಿಗಿಂತ ಕಡಿಮೆ ಅಥವಾ ಸಮವಾಗಿರಬೇಕು.',
    editFieldTargetDeposit: 'ಗುರಿ ಭದ್ರತಾ ಠೇವಣಿ (ಒಟ್ಟು ₹)',
    editFieldPaid: 'ಪ್ರಸ್ತುತ ಪಾವತಿಸಿದ್ದು (₹)',
    editFieldFullName: 'ಪೂರ್ಣ ಹೆಸರು',
    editFieldEmail: 'ಇಮೇಲ್',
    editFieldPhone: 'ಫೋನ್',
    editFieldIdNumber: 'ಐಡಿ ಸಂಖ್ಯೆ',
    editPlaceholderDeposit: 'ನಿರೀಕ್ಷಿತ ಒಟ್ಟು ಮೊತ್ತ',
    editHintDeposit: 'ಬಾಡಿಗೆದಾರರಿಂದ ನಿರೀಕ್ಷಿತ ಒಟ್ಟು ಮೊತ್ತ.',
    editPlaceholderPaid: '0',
    editPlaceholderName: 'ಬಾಡಿಗೆದಾರರ ಪೂರ್ಣ ಹೆಸರು',
    editPlaceholderEmail: 'tenant@example.com',
    editPlaceholderPhone: 'ಬಾಡಿಗೆದಾರರ ಫೋನ್',
    editPlaceholderId: 'ಆಧಾರ್ / ಸರ್ಕಾರಿ ಐಡಿ ಸಂಖ್ಯೆ',
    editSavedTitle: 'ಉಳಿಸಲಾಗಿದೆ',
    editSavedMsg: 'ಬಾಡಿಗೆದಾರರ ವಿವರ ನವೀಕರಿಸಲಾಗಿದೆ.',
    editErr: 'ನವೀಕರಣ ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    refundTitle: 'ರಿಫಂಡ್ ಪರಿಹಾರ ಎಂದು ಗುರುತಿಸಿ',
    refundFieldNote: 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)',
    refundPlaceholderNote: 'ಈ ರಿಫಂಡ್‌ಗೆ ಐಚ್ಛಿಕ ಟಿಪ್ಪಣಿ…',
    refundConfirm: 'ಪರಿಹಾರ ಎಂದು ಗುರುತಿಸಿ',
    refundAlertTitle: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    refundAlertMsg: 'ರಿಫಂಡ್ ಪರಿಹಾರ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.',
    refundErr: 'ರಿಫಂಡ್ ಪರಿಹರಿಸಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },
  addTenant: {
    title: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸೇರಿಸಿ',
    sub: 'ಬಾಡಿಗೆದಾರರನ್ನು ಕೋಣೆಗೆ ಸ್ಥಳಾಂತರಿಸಿ',
    sectionRoom: '1. ಕೋಣೆ ನಿಯೋಜಿಸಿ',
    sectionTenant: '2. ಬಾಡಿಗೆದಾರರು',
    sectionDetails: '3. ಬಾಡಿಗೆ ವಿವರಗಳು',
    selectRoomPlaceholder: 'ಖಾಲಿ ಕೋಣೆ ಆಯ್ಕೆಮಾಡಿ…',
    errRoomFull: 'ಈ ಕೋಣೆ ತುಂಬಿದೆ.',
    segmentExisting: 'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಬಳಕೆದಾರ',
    segmentNew: 'ಹೊಸದಾಗಿ ರಚಿಸಿ',
    selectUserPlaceholder: 'ನೋಂದಾಯಿತ ಬಳಕೆದಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ…',
    labelFullName: 'ಪೂರ್ಣ ಹೆಸರು *',
    labelEmail: 'ಇಮೇಲ್ *',
    placeholderName: 'ಬಾಡಿಗೆದಾರರ ಹೆಸರು',
    placeholderEmail: 'tenant@email.com',
    btnSendOtp: 'OTP ಕಳಿಸಿ',
    labelOtp: 'OTP',
    placeholderOtp: '6-ಅಂಕಿಯ',
    btnVerify: 'ಪರಿಶೀಲಿಸಿ',
    verified: 'ಇಮೇಲ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    labelPassword: 'ತಾತ್ಕಾಲಿಕ ಪಾಸ್‌ವರ್ಡ್ *',
    placeholderPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ',
    passwordHint: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು, ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ, ಸಂಖ್ಯೆ ಮತ್ತು ವಿಶೇಷ ಅಕ್ಷರ (@$!%*?&) ಅಗತ್ಯ',
    btnAccountCreated: 'ಖಾತೆ ರಚಿಸಲಾಗಿದೆ',
    btnCreateAccount: 'ಖಾತೆ ರಚಿಸಿ',
    labelPhone: 'ಫೋನ್ *',
    placeholderPhone: 'ಬಾಡಿಗೆದಾರರ ಫೋನ್',
    labelIdNumber: 'ಐಡಿ ಸಂಖ್ಯೆ',
    placeholderIdNumber: 'ಆಧಾರ್ / ಸರ್ಕಾರಿ ಐಡಿ ಸಂಖ್ಯೆ',
    labelJoinDate: 'ಸೇರಿದ ದಿನಾಂಕ *',
    placeholderJoinDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ…',
    labelSecurityDeposit: 'ಭದ್ರತಾ ಠೇವಣಿ (₹)',
    labelAdvancePaid: 'ಮುಂಗಡ ಪಾವತಿ (₹)',
    labelNotes: 'ಟಿಪ್ಪಣಿಗಳು',
    placeholderNotes: 'ಐಚ್ಛಿಕ ಟಿಪ್ಪಣಿ',
    btnSubmit: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸೇರಿಸಿ',
    alertRegisterTitle: 'ನೋಂದಣಿ ವಿಫಲ',
    alertRegisterMsg: 'ಖಾತೆ ರಚಿಸಲು ವಿಫಲ.',
    alertMissingTitle: 'ವಿವರ ಕಾಣೆಯಾಗಿದೆ',
    alertMissingName: 'ದಯವಿಟ್ಟು ಬಾಡಿಗೆದಾರರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.',
    alertInvalidNameTitle: 'ಅಮಾನ್ಯ ಹೆಸರು',
    alertInvalidNameMsg: 'ಹೆಸರು ಕನಿಷ್ಠ 2 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
    alertWeakPwTitle: 'ದುರ್ಬಲ ಪಾಸ್‌ವರ್ಡ್',
    alertWeakPwMin: 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
    alertWeakPwChars: 'ಪಾಸ್‌ವರ್ಡ್‌ನಲ್ಲಿ ದೊಡ್ಡ-ಸಣ್ಣ ಅಕ್ಷರ, ಸಂಖ್ಯೆ ಮತ್ತು ವಿಶೇಷ ಅಕ್ಷರ (@$!%*?&) ಇರಬೇಕು.',
    alertDone: 'ಆಯಿತು',
    alertDoneMsg: 'ಬಾಡಿಗೆದಾರರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ.',
    alertErr: 'ಬಾಡಿಗೆದಾರರನ್ನು ಸೇರಿಸಲು ವಿಫಲ.',
    selectRoomTitle: 'ಕೋಣೆ ಆಯ್ಕೆಮಾಡಿ',
    selectUserTitle: 'ಬಳಕೆದಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    userAlreadyActive: 'ಈಗಾಗಲೇ ಸಕ್ರಿಯ ಬಾಡಿಗೆದಾರ',
    selectDateTitle: 'ಸೇರಿದ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    occupancySuffix: '{{occupied}}/{{capacity}} ಆಕ್ರಮಿತ',
    rentPerMonth: '{{amount}}/ತಿಂಗಳು',
  },
  payments: {
    title: 'ಪಾವತಿಗಳು',
    headerSub: 'ಇಂದು ಸಂಗ್ರಹಿಸಿದ ₹{{amount}}',
    stripOverdue: 'ಮಿತಿಮೀರಿದೆ',
    stripPending: 'ಬಾಕಿ',
    stripCollected: 'ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
    tabAll: 'ಎಲ್ಲಾ',
    tabOverdue: 'ಮಿತಿಮೀರಿದೆ',
    tabPending: 'ಬಾಕಿ',
    tabPartial: 'ಭಾಗಶಃ',
    tabPaid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    searchPlaceholder: 'ಬಾಡಿಗೆದಾರ, ಕೋಣೆ, ತಿಂಗಳಿನಿಂದ ಹುಡುಕಿ…',
    emptyNoSearch: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಸಿಗಲಿಲ್ಲ',
    emptyNoRecords: '{{status}} ದಾಖಲೆಗಳಿಲ್ಲ',
    statusPending: 'ಬಾಕಿ',
    statusPartial: 'ಭಾಗಶಃ',
    statusOverdue: 'ಮಿತಿಮೀರಿದೆ',
    statusPaid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    amountTotal: 'ಒಟ್ಟು',
    amountPaid: 'ಪಾವತಿಸಿದೆ',
    amountRemaining: 'ಉಳಿದಿದೆ',
    proofAwaiting: 'ಪಾವತಿ ಪುರಾವೆ ಪರಿಶೀಲನೆಯ ನಿರೀಕ್ಷೆಯಲ್ಲಿದೆ',
    btnVerify: 'ಪರಿಶೀಲಿಸಿ',
    btnReject: 'ತಿರಸ್ಕರಿಸಿ',
    verifyAlertTitle: 'ಪಾವತಿ ಪರಿಶೀಲಿಸಿ',
    verifyAlertMsg: 'ಈ ಪಾವತಿ ಪುರಾವೆಯನ್ನು ದೃಢೀಕರಿಸಿ ಬಾಡಿಗೆದಾರರಿಗೆ ಜಮಾ ಮಾಡಬೇಕೆ?',
    verifyAlertConfirm: 'ಪರಿಶೀಲಿಸಿ',
    verifiedAlertTitle: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    verifiedAlertMsg: 'ಪಾವತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ಜಮಾ ಮಾಡಲಾಗಿದೆ.',
    rejectedAlertTitle: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    rejectedAlertMsg: 'ಪಾವತಿ ಪುರಾವೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ. ಬಾಡಿಗೆದಾರರಿಗೆ ತಿಳಿಸಲಾಗುತ್ತದೆ.',
    errVerify: 'ಪರಿಶೀಲನೆ ವಿಫಲ.',
    errReject: 'ತಿರಸ್ಕರಣೆ ವಿಫಲ.',
    rejectModalTitle: 'ಪಾವತಿ ತಿರಸ್ಕರಿಸಿ',
    rejectModalSub: 'ಬಾಡಿಗೆದಾರರಿಗೆ ಅವರ ಪುರಾವೆ ಏಕೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ ಎಂದು ತಿಳಿಸಲು ಕಾರಣ ನೀಡಿ.',
    rejectPlaceholder: 'ಉದಾ: ಮಸುಕಾದ ಚಿತ್ರ, ತಪ್ಪು ಮೊತ್ತ…',
    btnCancel: 'ರದ್ದುಮಾಡಿ',
  },
  approvals: {
    title: 'ಬಾಕಿ ಅನುಮೋದನೆಗಳು',
    count_one: '{{count}} ಪರಿಶೀಲನೆಗಾಗಿ ನಿರೀಕ್ಷೆಯಲ್ಲಿದೆ',
    count_other: '{{count}} ಪರಿಶೀಲನೆಗಳಿಗಾಗಿ ನಿರೀಕ್ಷೆಯಲ್ಲಿದೆ',
    allCaughtTitle: 'ಎಲ್ಲವೂ ಮುಗಿಯಿತು!',
    allCaughtSub: 'ಯಾವುದೇ ಪಾವತಿ ಪುರಾವೆ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿಲ್ಲ.',
    btnApprove: 'ಅನುಮೋದಿಸಿ',
    btnReject: 'ತಿರಸ್ಕರಿಸಿ',
    rejectTitle: 'ಪಾವತಿ ತಿರಸ್ಕರಿಸಿ',
    rejectSub: 'ಬಾಡಿಗೆದಾರರಿಗೆ ಅವರ ಪುರಾವೆ ಏಕೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ ಎಂದು ತಿಳಿಸಲು ಕಾರಣ ನೀಡಿ.',
    rejectPlaceholder: 'ಉದಾ: ತಪ್ಪು ಮೊತ್ತ, ಮಸುಕಾದ ಚಿತ್ರ…',
    btnCancel: 'ರದ್ದುಮಾಡಿ',
    errVerify: 'ಪರಿಶೀಲನೆ ವಿಫಲ.',
    errReject: 'ತಿರಸ್ಕರಣೆ ವಿಫಲ.',
  },
  transactions: {
    fallbackTitle: 'ಪಾವತಿ',
    totalCollected: 'ಒಟ್ಟು ಸಂಗ್ರಹ',
    floatBanner: 'ಫ್ಲೋಟಿಂಗ್ ಬಾಕಿ: {{amount}} ಮುಂದಕ್ಕೆ ಒಯ್ಯಲಾಗುತ್ತಿದೆ',
    proofAwaiting: 'ಪಾವತಿ ಪುರಾವೆ ಪರಿಶೀಲನೆಯ ನಿರೀಕ್ಷೆಯಲ್ಲಿದೆ',
    sectionTransactions: 'ವಹಿವಾಟುಗಳು',
    emptyTitle: 'ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟು ದಾಖಲಾಗಿಲ್ಲ.',
    btnRecordPayment: 'ಪಾವತಿ ದಾಖಲಿಸಿ',
    addPaymentTitle: 'ಪಾವತಿ ದಾಖಲಿಸಿ',
    fieldAmount: 'ಮೊತ್ತ (₹) *',
    fieldMethod: 'ಪಾವತಿ ವಿಧಾನ *',
    methodCash: 'ನಗದು',
    methodUpi: 'UPI',
    methodBank: 'ಬ್ಯಾಂಕ್',
    methodCheque: 'ಚೆಕ್',
    fieldDate: 'ಪಾವತಿ ದಿನಾಂಕ *',
    placeholderDate: 'YYYY-MM-DD',
    fieldNotes: 'ಟಿಪ್ಪಣಿಗಳು',
    placeholderNotes: 'ಐಚ್ಛಿಕ ಉಲ್ಲೇಖ',
    btnAttachProof: 'ಪಾವತಿ ಪುರಾವೆ ಲಗತ್ತಿಸಿ (ಐಚ್ಛಿಕ)',
    btnCancel: 'ರದ್ದುಮಾಡಿ',
    btnRecord: 'ಪಾವತಿ ದಾಖಲಿಸಿ',
    btnVerify: 'ಪರಿಶೀಲಿಸಿ',
    btnReject: 'ತಿರಸ್ಕರಿಸಿ',
    btnReverse: 'ಈ ಪಾವತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    btnUndoReversal: 'ರದ್ದತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ',
    refLabel: 'ರೆಫ್: {{ref}}',
    recordedBy: '{{name}} ({{role}}) ದಾಖಲಿಸಿದ್ದಾರೆ',
    alertPermissionTitle: 'ಅನುಮತಿ',
    alertPermissionMsg: 'ಪುರಾವೆ ಲಗತ್ತಿಸಲು ಗ್ಯಾಲರಿ ಅನುಮತಿ ಅಗತ್ಯ.',
    alertErrRecord: 'ಪಾವತಿ ದಾಖಲಿಸಲು ವಿಫಲ.',
    errVerify: 'ಪರಿಶೀಲನೆ ವಿಫಲ.',
    errReject: 'ತಿರಸ್ಕರಣೆ ವಿಫಲ.',
    errReverse: 'ರದ್ದತಿ ವಿಫಲ.',
    errUndo: 'ರದ್ದತಿ ರದ್ದುಗೊಳಿಸಲು ವಿಫಲ.',
    errLoad: 'ಪಾವತಿ ವಿವರ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ',
    btnRetry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    reversedAlertTitle: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    reversedAlertMsg: 'ಪಾವತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ.',
    undoneAlertTitle: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    undoneAlertMsg: 'ರದ್ದತಿ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ಪಾವತಿ ಮರಳಿ ಅನ್ವಯಿಸಲಾಗಿದೆ.',
    undoTitle: 'ರದ್ದತಿ ರದ್ದುಗೊಳಿಸಿ',
    undoMsg: '{{amount}} ಅನ್ನು ಮರಳಿ ಈ ದಾಖಲೆಗೆ ಅನ್ವಯಿಸಬೇಕೆ?',
    undoConfirm: 'ರದ್ದುಗೊಳಿಸಿ',
    reverseTitle: 'ಪಾವತಿ ರದ್ದುಗೊಳಿಸಿ',
    reverseSub: '{{date}} ರಂದು {{amount}} ದಾಖಲಾಗಿದೆ',
    reversePlaceholder: 'ರದ್ದತಿಗೆ ಕಾರಣ (ಅಗತ್ಯ)',
    reverseBtn: 'ರದ್ದುಗೊಳಿಸಿ',
    btnCancel2: 'ರದ್ದುಮಾಡಿ',
    statusCompleted: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    statusVerifying: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
    statusReversed: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    statusFailed: 'ವಿಫಲ',
    floatMovedOut: 'ಫ್ಲೋಟಿಂಗ್ ಮೊತ್ತ −{{amount}} ಈ ತಿಂಗಳಿನಿಂದ ಹೊರಗೆ',
    floatMovedIn: 'ಫ್ಲೋಟಿಂಗ್ ಮೊತ್ತ +{{amount}} ಈ ತಿಂಗಳಿಗೆ ತರಲಾಗಿದೆ',
  },
  complaints: {
    title: 'ದೂರುಗಳು',
    count_one: '{{count}} ದೂರು',
    count_other: '{{count}} ದೂರುಗಳು',
    tabAll: 'ಎಲ್ಲಾ',
    tabOpen: 'ತೆರೆದಿದೆ',
    tabInProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    tabResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    searchPlaceholder: 'ಶೀರ್ಷಿಕೆ ಅಥವಾ ಬಾಡಿಗೆದಾರರಿಂದ ಹುಡುಕಿ…',
    emptyNoSearch: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಸಿಗಲಿಲ್ಲ',
    emptyDefault: 'ಇಲ್ಲಿ ಯಾವುದೇ ದೂರುಗಳಿಲ್ಲ',
    statusOpen: 'ತೆರೆದಿದೆ',
    statusInProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    statusResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    statusRejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    statusClosed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    priorityLow: 'ಕಡಿಮೆ',
    priorityMedium: 'ಮಧ್ಯಮ',
    priorityHigh: 'ಹೆಚ್ಚು',
    priorityUrgent: 'ತುರ್ತು',
    noLocation: 'ಸ್ಥಳ ಇಲ್ಲ',
  },
  complaintDetail: {
    title: 'ದೂರು',
    errLoad: 'ದೂರು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ',
    btnRetry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    badgePrioritySuffix: '{{label}} ಆದ್ಯತೆ',
    resolutionNotes: 'ಪರಿಹಾರ ಟಿಪ್ಪಣಿಗಳು',
    sectionUpdateStatus: 'ಸ್ಥಿತಿ ನವೀಕರಿಸಿ',
    fieldResolutionNotes: 'ಪರಿಹಾರ ಟಿಪ್ಪಣಿಗಳು *',
    placeholderResolution: 'ಪರಿಹಾರವನ್ನು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ವಿವರಿಸಿ…',
    btnUpdateStatus: 'ಸ್ಥಿತಿ ನವೀಕರಿಸಿ',
    sectionComments: 'ಟಿಪ್ಪಣಿಗಳು',
    sectionCommentsCount: 'ಟಿಪ್ಪಣಿಗಳು ({{count}})',
    noComments: 'ಇನ್ನೂ ಯಾವುದೇ ಟಿಪ್ಪಣಿಗಳಿಲ್ಲ. ಕೆಳಗೆ ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ.',
    composerClosed: 'ಈ ದೂರು ಮುಚ್ಚಲಾಗಿದೆ',
    composerReply: 'ಬಾಡಿಗೆದಾರರಿಗೆ ಉತ್ತರಿಸಿ…',
    statusInProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    statusResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    statusRejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
  },
  expenses: {
    title: 'ಖರ್ಚುಗಳು',
    add: 'ಸೇರಿಸಿ',
    addBtn: 'ಖರ್ಚು ಸೇರಿಸಿ',
    headerSub: "{{month}} ಈ ತಿಂಗಳ ನಿವ್ವಳ ಲಾಭ",
    allProperties: 'ಎಲ್ಲಾ ಆಸ್ತಿಗಳು',
    netProfit: 'ನಿವ್ವಳ ಲಾಭ',
    rentCollected: 'ಸಂಗ್ರಹಿತ ಬಾಡಿಗೆ',
    totalExpenses: 'ಒಟ್ಟು ಖರ್ಚುಗಳು',
    expenseCount: 'ಖರ್ಚುಗಳ ಸಂಖ್ಯೆ',
    sectionRecurring: 'ಆವರ್ತಕ ಮಾಸಿಕ',
    emptyRecurring: 'ಯಾವುದೇ ಆವರ್ತಕ ಖರ್ಚು ಹೊಂದಿಸಿಲ್ಲ.',
    sectionExpenses: 'ಖರ್ಚುಗಳು',
    emptyForMonth: '{{month}} ಗೆ ಯಾವುದೇ ಖರ್ಚಿಲ್ಲ.',
    emptyTapAdd: 'ದಾಖಲಿಸಲು ಸೇರಿಸು ಒತ್ತಿ.',
    btnLogged: 'ದಾಖಲಾಗಿದೆ',
    btnLogMonth: 'ಈ ತಿಂಗಳು ದಾಖಲಿಸಿ',
    tagMonthly: 'ಮಾಸಿಕ',
    addExpenseTitle: 'ಖರ್ಚು ಸೇರಿಸಿ',
    editExpenseTitle: 'ಖರ್ಚು ಸಂಪಾದಿಸಿ',
    fieldProperty: 'ಆಸ್ತಿ *',
    placeholderProperty: 'ಆಸ್ತಿ ಆಯ್ಕೆಮಾಡಿ…',
    selectPropertyTitle: 'ಆಸ್ತಿ ಆಯ್ಕೆಮಾಡಿ',
    fieldCategory: 'ವರ್ಗ *',
    fieldTitle: 'ಶೀರ್ಷಿಕೆ',
    placeholderTitle: 'ಉದಾ: ನೀರಿನ ಪಂಪ್ ದುರಸ್ತಿ',
    fieldAmount: 'ಮೊತ್ತ *',
    placeholderAmount: '0',
    fieldMonth: 'ತಿಂಗಳು',
    placeholderMonth: 'YYYY-MM',
    fieldExpenseDate: 'ಖರ್ಚಿನ ದಿನಾಂಕ',
    placeholderExpenseDate: 'YYYY-MM-DD',
    fieldNotes: 'ಟಿಪ್ಪಣಿಗಳು',
    placeholderNotes: 'ಐಚ್ಛಿಕ ಟಿಪ್ಪಣಿ…',
    recurringTitle: 'ಆವರ್ತಕ ಮಾಸಿಕ ಖರ್ಚು',
    recurringSub: 'ಪ್ರತಿ ತಿಂಗಳು ಈ ಮೊತ್ತವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ದಾಖಲಿಸಿ',
    btnCancel: 'ರದ್ದುಮಾಡಿ',
    btnSaveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    btnAddExpense: 'ಖರ್ಚು ಸೇರಿಸಿ',
    catMaintenance: 'ನಿರ್ವಹಣೆ',
    catElectricity: 'ವಿದ್ಯುತ್',
    catWater: 'ನೀರು',
    catSociety: 'ಸೊಸೈಟಿ',
    catRepairs: 'ದುರಸ್ತಿ',
    catCleaning: 'ಸ್ವಚ್ಛತೆ',
    catInternet: 'ಇಂಟರ್ನೆಟ್',
    catMisc: 'ಇತರ',
    alertOfflineSave: 'ಆಫ್‌ಲೈನ್ ಉಳಿಸಲಾಗಿದೆ',
    alertOfflineSaveMsg: 'ಖರ್ಚು ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸ್ವಯಂ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    alertOfflineUpdateMsg: 'ಬದಲಾವಣೆಗಳು ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    alertOfflineDeleteTitle: 'ಆಫ್‌ಲೈನ್ ಅಳಿಸಲಾಗಿದೆ',
    alertOfflineDeleteMsg: 'ಖರ್ಚು ಈ ಸಾಧನದಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸ್ವಯಂ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    alertOfflineRecurMsg: 'ಆವರ್ತಕ ಖರ್ಚು ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    alertOfflineRecurLogMsg: 'ಈ ತಿಂಗಳ ಆವರ್ತಕ ಖರ್ಚು ಈ ಸಾಧನದಲ್ಲಿ ಸೇರಿಸಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    alertAdded: 'ಸೇರಿಸಲಾಗಿದೆ',
    alertAddedMsg: 'ಖರ್ಚು ದಾಖಲಾಗಿದೆ.',
    alertUpdated: 'ನವೀಕರಿಸಲಾಗಿದೆ',
    alertUpdatedMsg: 'ಖರ್ಚು ನವೀಕರಿಸಲಾಗಿದೆ.',
    alertDeleted: 'ಅಳಿಸಲಾಗಿದೆ',
    alertDeletedMsg: 'ಖರ್ಚು ತೆಗೆದುಹಾಕಲಾಗಿದೆ.',
    alertLogged: 'ದಾಖಲಾಗಿದೆ',
    alertLoggedMsg: 'ಈ ತಿಂಗಳ ಆವರ್ತಕ ಖರ್ಚು ಸೇರಿಸಲಾಗಿದೆ.',
    errAdd: 'ಖರ್ಚು ಸೇರಿಸಲು ವಿಫಲ.',
    errUpdate: 'ಖರ್ಚು ನವೀಕರಿಸಲು ವಿಫಲ.',
    errDelete: 'ಖರ್ಚು ಅಳಿಸಲು ವಿಫಲ.',
    errLogRecur: 'ಆವರ್ತಕ ಖರ್ಚು ದಾಖಲಿಸಲು ವಿಫಲ.',
    deleteTitle: 'ಖರ್ಚು ಅಳಿಸಿ',
    deleteMsg: '"{{title}}" ({{amount}}) ತೆಗೆದುಹಾಕಬೇಕೆ?',
    btnDelete: 'ಅಳಿಸಿ',
    missingPropTitle: 'ಆಸ್ತಿ ಕಾಣೆಯಾಗಿದೆ',
    missingPropMsg: 'ಈ ಆವರ್ತಕ ಖರ್ಚಿಗೆ ಯಾವುದೇ ಆಸ್ತಿ ಇಲ್ಲ. ದಯವಿಟ್ಟು ಕೈಯಾರೆ ಸೇರಿಸಿ.',
    alreadyLoggedTitle: 'ಈಗಾಗಲೇ ದಾಖಲಾಗಿದೆ',
    alreadyLoggedMsg: 'ಈ ಆವರ್ತಕ ಖರ್ಚು {{month}} ಗೆ ಈಗಾಗಲೇ ದಾಖಲಾಗಿದೆ.',
    expenseFallback: 'ಖರ್ಚು',
    recurringFallback: 'ಆವರ್ತಕ ಖರ್ಚು',
  },
  reports: {
    title: 'ವರದಿಗಳು',
    btnPdf: 'PDF',
    profitSummary: 'ಲಾಭ ಸಾರಾಂಶ',
    rentCollected: 'ಸಂಗ್ರಹಿತ ಬಾಡಿಗೆ',
    expenses: 'ಖರ್ಚುಗಳು',
    netProfit: 'ನಿವ್ವಳ ಲಾಭ',
    expenseRecorded: 'ಈ ತಿಂಗಳು {{count}} ಖರ್ಚುಗಳು ದಾಖಲಾಗಿದೆ',
    sectionBreakdown: 'ಆದಾಯ ಮತ್ತು ಖರ್ಚು ವಿವರ',
    totalIncome: 'ಒಟ್ಟು ಆದಾಯ',
    emptyExp: 'ಈ ಅವಧಿಗೆ ಯಾವುದೇ ಖರ್ಚು ದಾಖಲಾಗಿಲ್ಲ.',
    recurringSuffix: ' · ಆವರ್ತಕ',
    errExport: 'ವರದಿ ರಫ್ತು ಮಾಡಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },
  profile: {
    title: 'ಪ್ರೊಫೈಲ್',
    sub: 'ಪಾವತಿ ಮತ್ತು ಖಾತೆ ವಿವರ ನಿರ್ವಹಿಸಿ',
    roleBadge: 'ಮಾಲೀಕರು',
    sectionQr: 'ಪಾವತಿ QR ಕೋಡ್',
    qrSub: 'ಬಾಡಿಗೆದಾರರು ಈ QR ಅನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ನಿಮಗೆ ಬಾಡಿಗೆ ಪಾವತಿಸುತ್ತಾರೆ.',
    qrPlaceholder: 'ಇನ್ನೂ QR ಅಪ್‌ಲೋಡ್ ಆಗಿಲ್ಲ',
    btnUploadQr: 'QR ಅಪ್‌ಲೋಡ್ / ಬದಲಾಯಿಸಿ',
    sectionUpi: 'UPI ಪಾವತಿ ವಿವರ',
    fieldUpiId: 'UPI ಐಡಿ',
    fieldUpiName: 'ನೋಂದಾಯಿತ ಹೆಸರು',
    fieldUpiNumber: 'UPI ಸಂಖ್ಯೆ',
    btnSaveUpi: 'UPI ವಿವರ ಉಳಿಸಿ',
    sectionBank: 'ಬ್ಯಾಂಕ್ ವಿವರ',
    bankSub: 'ಹಿಂತಿರುಗಿಸುವಿಕೆ ಮತ್ತು ಬಾಡಿಗೆ ಪಾವತಿಗಳಿಗಾಗಿ.',
    fieldAccountHolder: 'ಖಾತೆದಾರ',
    fieldAccountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ',
    fieldBankName: 'ಬ್ಯಾಂಕ್ ಹೆಸರು',
    fieldIfsc: 'IFSC ಕೋಡ್',
    btnSaveBank: 'ಬ್ಯಾಂಕ್ ವಿವರ ಉಳಿಸಿ',
    sectionAccount: 'ಖಾತೆ',
    btnSignOut: 'ಸೈನ್ ಔಟ್',
    alertSavedTitle: 'ಉಳಿಸಲಾಗಿದೆ',
    alertSavedUpiMsg: 'UPI ಪಾವತಿ ವಿವರ ನವೀಕರಿಸಲಾಗಿದೆ.',
    alertSavedBankMsg: 'ಬ್ಯಾಂಕ್ ವಿವರ ನವೀಕರಿಸಲಾಗಿದೆ.',
    alertQrTitle: 'ಆಯಿತು',
    alertQrMsg: 'ಪಾವತಿ QR ಕೋಡ್ ನವೀಕರಿಸಲಾಗಿದೆ. ಬಾಡಿಗೆದಾರರು ಈಗ ಈ QR ಅನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿಸಬಹುದು.',
    alertErrUpi: 'UPI ವಿವರ ಉಳಿಸಲು ವಿಫಲ.',
    alertErrBank: 'ಬ್ಯಾಂಕ್ ವಿವರ ಉಳಿಸಲು ವಿಫಲ.',
    alertErrQr: 'QR ಕೋಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ವಿಫಲ.',
    alertPermissionTitle: 'ಅನುಮತಿ',
    alertPermissionMsg: 'ಗ್ಯಾಲರಿ ಅನುಮತಿ ಅಗತ್ಯ.',
  },
  placeholder: {
    comingSoon: 'ಈ ಪರದೆ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ.',
  },
};

function loadFile(lang) {
  const fp = path.join(__dirname, 'src', 'localization', 'translations', `${lang}.json`);
  let raw = fs.readFileSync(fp, 'utf8');
  let bom = false;
  if (raw.charCodeAt(0) === 0xFEFF) { bom = true; raw = raw.slice(1); }
  const data = JSON.parse(raw);
  return { fp, bom, data };
}

function deepMergeInto(target, source) {
  for (const key of Object.keys(source)) {
    const tv = target[key];
    const sv = source[key];
    const tvIsObj = tv !== null && typeof tv === 'object' && !Array.isArray(tv);
    const svIsObj = sv !== null && typeof sv === 'object' && !Array.isArray(sv);
    if (svIsObj && tvIsObj) {
      deepMergeInto(tv, sv);
    } else if (!(key in target) || (svIsObj && !tvIsObj)) {
      target[key] = sv;
    }
  }
  return target;
}

const { fp, bom, data } = loadFile('kn');
if (!data.owner) data.owner = {};
deepMergeInto(data.owner, KN);
const out = JSON.stringify(data, null, 2) + '\n';
fs.writeFileSync(fp, (bom ? '﻿' : '') + out, 'utf8');
console.log('✓ kn:', Object.keys(data.owner).filter(k => typeof data.owner[k] === 'object').length, 'nested keys');
