// One-shot script: adds Malayalam translations for all owner portal keys.
const fs = require('fs');
const path = require('path');

const ML = {
  commonOwner: {
    saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    remove: 'നീക്കം ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    error: 'പിശക്',
    verified: 'പരിശോധിച്ചു',
    rejected: 'നിരസിച്ചു',
    property: 'സ്വത്ത്',
    floor: 'നില',
    add: 'ചേർക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    yes: 'ഉവ്വ്',
    no: 'ഇല്ല',
    notes: 'കുറിപ്പുകൾ',
    room: 'മുറി',
    months: 'മാസങ്ങൾ',
  },
  drawer: {
    ownerDashboard: 'ഡാഷ്ബോർഡ്',
    ownerProperties: 'സ്വത്തുക്കൾ',
    ownerTenants: 'വാടകക്കാർ',
    ownerAddTenant: 'വാടകക്കാരനെ ചേർക്കുക',
    ownerPayments: 'പേയ്‌മെന്റുകൾ',
    ownerApprovals: 'തീർപ്പാക്കാത്ത അംഗീകാരങ്ങൾ',
    ownerComplaints: 'പരാതികൾ',
    ownerExpenses: 'ചെലവുകൾ',
    ownerReports: 'റിപ്പോർട്ടുകൾ',
    ownerNotifications: 'അറിയിപ്പുകൾ',
    helpCenter: 'സഹായ കേന്ദ്രം',
    about: 'Happy Renting നെക്കുറിച്ച്',
    visitWebsite: 'വെബ്‌സൈറ്റ് സന്ദർശിക്കുക',
    rateApp: 'ആപ്പ് റേറ്റ് ചെയ്യുക',
    shareApp: 'Happy Renting പങ്കിടുക',
    shareMessage: 'Happy Renting ഉപയോഗിച്ച് വാടകയും ബില്ലുകളും നിങ്ങളുടെ സ്വത്തും എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യൂ! ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ: https://play.google.com/store/apps/details?id=co.in.happyrenting.tenant',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    termsOfService: 'സേവന നിബന്ധനകൾ',
    logout: 'ലോഗൗട്ട്',
    logoutConfirmTitle: 'ലോഗൗട്ട്',
    logoutConfirmMsg: 'നിങ്ങൾക്ക് ലോഗൗട്ട് ചെയ്യണോ?',
    shareErrorMsg: 'ആപ്പ് ലിങ്ക് പങ്കിടാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    ownerWorkspace: 'ഉടമയുടെ വർക്ക്‌സ്‌പേസ്',
    tenantWorkspace: 'വാടകക്കാരന്റെ വർക്ക്‌സ്‌പേസ്',
  },
  dashboard: {
    title: 'ഡാഷ്ബോർഡ്',
    welcome: 'തിരികെ സ്വാഗതം, {{name}}',
    totalCollected: 'ആകെ ശേഖരം',
    today: 'ഇന്ന്',
    overdue: 'കാലഹരണപ്പെട്ടു',
    outstanding: 'കുടിശ്ശിക',
    netCollectionMonth: 'ഈ മാസത്തെ അറ്റ ശേഖരം',
    collected: 'ശേഖരിച്ചു',
    expenses: 'ചെലവുകൾ',
    entries: 'എൻട്രികൾ',
    overview: 'അവലോകനം',
    properties: 'സ്വത്തുക്കൾ',
    rooms: 'മുറികൾ',
    activeTenants: 'സജീവ വാടകക്കാർ',
    occupancy: 'താമസ നിരക്ക്',
    paidBills: 'അടച്ച ബില്ലുകൾ',
    overdueBills: 'കാലഹരണപ്പെട്ട ബില്ലുകൾ',
    paymentBreakdown: 'പേയ്‌മെന്റ് വിശദാംശങ്ങൾ',
    pendingBills: 'തീർപ്പാക്കാത്ത ബില്ലുകൾ',
    partialPayments: 'ഭാഗിക പേയ്‌മെന്റുകൾ',
    overdueBillsBreakdown: 'കാലഹരണപ്പെട്ട ബില്ലുകൾ',
    totalOutstanding: 'ആകെ കുടിശ്ശിക',
    seeAll: 'എല്ലാം കാണുക',
    loadError: 'അനലിറ്റിക്സ് ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല. പുനഃശ്രമിക്കാൻ താഴേക്ക് വലിക്കുക.',
  },
  properties: {
    title: 'സ്വത്തുക്കൾ',
    count_one: '{{count}} സ്വത്ത്',
    count_other: '{{count}} സ്വത്തുക്കൾ',
    add: 'ചേർക്കുക',
    addBtn: 'സ്വത്ത് ചേർക്കുക',
    addTitle: 'സ്വത്ത് ചേർക്കുക',
    editTitle: 'സ്വത്ത് എഡിറ്റ് ചെയ്യുക',
    fieldName: 'സ്വത്തിന്റെ പേര് *',
    fieldAddress: 'വിലാസം *',
    fieldCity: 'നഗരം',
    placeholderName: 'ഉദാ: ഗ്രീൻ വാലി അപ്പാർട്ട്‌മെന്റ്',
    placeholderAddress: 'തെരുവ്, പ്രദേശം, ലാൻഡ്‌മാർക്ക്…',
    placeholderCity: 'ഉദാ: കൊച്ചി',
    cancel: 'റദ്ദാക്കുക',
    save: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    saveAdd: 'സ്വത്ത് ചേർക്കുക',
    removeTitle: 'സ്വത്ത് നീക്കം ചെയ്യുക',
    removeMsg: '"{{name}}" നീക്കം ചെയ്യണോ? ഇത് സ്വത്ത് നിഷ്ക്രിയമാക്കും. വാടകക്കാരുടെയും മുറിയുടെയും ഡാറ്റ സുരക്ഷിതമായിരിക്കും.',
    errCreate: 'സ്വത്ത് സൃഷ്ടിക്കുന്നതിൽ പരാജയം.',
    errUpdate: 'സ്വത്ത് അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയം.',
    errRemove: 'സ്വത്ത് നീക്കുന്നതിൽ പരാജയം.',
    loading: 'സ്വത്തുക്കൾ ലോഡ് ചെയ്യുന്നു…',
    emptyTitle: 'ഇതുവരെ സ്വത്തുക്കളൊന്നുമില്ല',
    emptyBody: 'ആദ്യ സ്വത്ത് സൃഷ്ടിക്കാൻ ചേർക്കുക ബട്ടൺ അമർത്തുക.',
    statsTotal: 'ആകെ',
    statsOccupied: 'താമസിച്ചു',
    statsVacant: 'ഒഴിഞ്ഞു',
    statsOccupancy: 'താമസ നിരക്ക്',
    noRooms: 'ഇതുവരെ മുറികളൊന്നുമില്ല. മുറികൾ ചേർക്കാൻ കാർഡ് അമർത്തുക.',
  },
  rooms: {
    title: 'മുറികൾ',
    add: 'ചേർക്കുക',
    addBtn: 'മുറി ചേർക്കുക',
    addTitle: 'മുറി ചേർക്കുക',
    editTitle: 'മുറി എഡിറ്റ് ചെയ്യുക',
    fieldRoomNumber: 'മുറി നമ്പർ *',
    fieldFloor: 'നില',
    fieldCapacity: 'ശേഷി *',
    fieldMonthlyRent: 'മാസിക വാടക (₹)',
    fieldSecurityDeposit: 'സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ് (₹)',
    fieldDescription: 'വിവരണം',
    placeholderRoomNumber: 'ഉദാ: 101',
    placeholderFloor: 'ഉദാ: ഗ്രൗണ്ട്',
    placeholderDescription: 'ഐച്ഛിക കുറിപ്പ്',
    infoOccupied: '{{occupied}}/{{capacity}} താമസിച്ചു · ശേഷി താമസ നിരക്കിനേക്കാൾ കുറയ്ക്കാൻ കഴിയില്ല',
    errCapacityMin: 'ശേഷി കുറഞ്ഞത് {{min}} ആയിരിക്കണം',
    cancel: 'റദ്ദാക്കുക',
    saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    saveAdd: 'മുറി ചേർക്കുക',
    removeTitle: 'മുറി നീക്കം ചെയ്യുക',
    removeMsg: 'മുറി {{number}} നീക്കം ചെയ്യണോ? മുറി ഒഴിഞ്ഞിട്ടുണ്ടെങ്കിൽ ഇത് റദ്ദാക്കാൻ കഴിയില്ല.',
    errCreate: 'മുറി സൃഷ്ടിക്കുന്നതിൽ പരാജയം.',
    errUpdate: 'മുറി അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയം.',
    errRemove: 'മുറി നീക്കുന്നതിൽ പരാജയം.',
    emptyTitle: 'ഇതുവരെ മുറികളൊന്നുമില്ല',
    emptySub: 'ആദ്യ മുറി സൃഷ്ടിക്കാൻ ചേർക്കുക അമർത്തുക.',
    propertyFallback: 'സ്വത്ത്',
    count_one: '{{count}} മുറി',
    count_other: '{{count}} മുറികൾ',
    floorPrefix: '· നില {{floor}}',
    rent: 'വാടക {{amount}}',
    deposit: 'ഡെപ്പോസിറ്റ് {{amount}}',
    badgeFull: 'നിറഞ്ഞു',
    badgeAvailable: 'ലഭ്യമാണ്',
    occupiedCount: '{{occupied}}/{{capacity}} താമസിച്ചു',
  },
  tenants: {
    title: 'വാടകക്കാർ',
    add: 'ചേർക്കുക',
    addBtn: 'വാടകക്കാരനെ ചേർക്കുക',
    count_one: '{{count}} ആകെ',
    count_other: '{{count}} ആകെ',
    countActive_one: '{{count}} സജീവം',
    countActive_other: '{{count}} സജീവം',
    countVacated_one: '{{count}} ഒഴിഞ്ഞു',
    countVacated_other: '{{count}} ഒഴിഞ്ഞു',
    tabActive: 'സജീവം',
    tabVacated: 'ഒഴിഞ്ഞു',
    tabAll: 'എല്ലാം',
    searchPlaceholder: 'പേര്, മുറി, സ്വത്ത് എന്നിവയിൽ നിന്ന് തിരയുക…',
    emptyNoSearch: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    emptyNoTenants: 'വാടകക്കാരൊന്നുമില്ല',
    emptyNoActive: 'സജീവ വാടകക്കാരൊന്നുമില്ല',
    emptyNoVacated: 'ഒഴിഞ്ഞ വാടകക്കാരൊന്നുമില്ല',
    detailRoom: 'മുറി',
    detailProperty: 'സ്വത്ത്',
    detailMonthlyRent: 'മാസിക വാടക',
    detailMoveIn: 'ചേർന്ന തീയതി',
    detailExit: 'പോകുന്ന തീയതി',
    detailPhone: 'ഫോൺ',
    detailIdNumber: 'ഐഡി നമ്പർ',
    detailSecurityDeposit: 'സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ്',
    detailAdvancePaid: 'അഡ്വാൻസ് അടച്ചു',
    detailNotes: 'കുറിപ്പുകൾ',
    detailEdit: 'വിശദാംശങ്ങൾ എഡിറ്റ് ചെയ്യുക',
    detailMoveOut: 'വാടകക്കാരനെ ഒഴിപ്പിക്കുക',
    detailReverse: 'ഒഴിപ്പിക്കൽ മാറ്റുക',
    refundDue: 'റീഫണ്ട് കുടിശ്ശിക',
    refundSettled: 'റീഫണ്ട് തീർക്കപ്പെട്ടു',
    markSettled: 'തീർത്തതായി അടയാളപ്പെടുത്തുക',
    statusActive: 'സജീവം',
    statusVacated: 'ഒഴിഞ്ഞു',
    statusPendingDeletion: 'ഇല്ലാതാക്കാൻ തീർപ്പാക്കാത്തത്',
    since: '{{date}} മുതൽ',
    moveOutTitle: 'വാടകക്കാരനെ ഒഴിപ്പിക്കുക',
    moveOutFieldExitDate: 'പോകുന്ന തീയതി *',
    moveOutFieldNotes: 'കുറിപ്പുകൾ (ഐച്ഛികം)',
    moveOutPlaceholderNotes: 'ഒഴിപ്പിക്കാനുള്ള കാരണം…',
    moveOutConfirm: 'ഒഴിപ്പിക്കൽ സ്ഥിരീകരിക്കുക',
    moveOutAlertTitle: 'ശരി',
    moveOutAlertMsg: 'വാടകക്കാരൻ വിജയകരമായി ഒഴിപ്പിച്ചു.',
    moveOutErr: 'ഒഴിപ്പിക്കുന്നതിൽ പരാജയം. വീണ്ടും ശ്രമിക്കുക.',
    moveOutEmptyExitDate: 'പോകുന്ന തീയതി',
    reverseAlertTitle: 'ഒഴിപ്പിക്കൽ മാറ്റുക',
    reverseAlertMsg: '{{name}} (മുറി {{room}}) വീണ്ടും സജീവമാക്കണോ? ഇത് മുറി വീണ്ടും താമസിക്കുന്നതാക്കും.',
    reverseAlertRestore: 'പുനഃസ്ഥാപിക്കുക',
    reverseDeletedTitle: 'ഒഴിപ്പിക്കൽ മാറ്ടാൻ കഴിയില്ല',
    reverseDeletedMsg: 'ഈ വാടകക്കാരന്റെ അക്കൗണ്ട് ഇല്ലാതാക്കി. ഒഴിപ്പിക്കൽ മാറ്റാൻ കഴിയില്ല.',
    reverseOk: 'ശരി',
    reverseDoneTitle: 'മാറ്റി',
    reverseDoneMsg: 'വാടകക്കാരൻ സജീവ അവസ്ഥയിലേക്ക് മടങ്ങി.',
    reverseErr: 'മാറ്റുന്നതിൽ പരാജയം. വീണ്ടും ശ്രമിക്കുക.',
    editTitle: 'വാടകക്കാരനെ എഡിറ്റ് ചെയ്യുക',
    editTabFinance: 'ധനകാര്യം',
    editTabProfile: 'പ്രൊഫൈൽ',
    editErrAdvanceDeposit: 'അഡ്വാൻസ് പേയ്‌മെന്റ് സെക്യൂരിറ്റി ഡെപ്പോസിറ്റിനേക്കാൾ കുറവോ തുല്യമോ ആയിരിക്കണം.',
    editFieldTargetDeposit: 'ലക്ഷ്യ സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ് (ആകെ ₹)',
    editFieldPaid: 'നിലവിൽ അടച്ചത് (₹)',
    editFieldFullName: 'മുഴുവൻ പേര്',
    editFieldEmail: 'ഇമെയിൽ',
    editFieldPhone: 'ഫോൺ',
    editFieldIdNumber: 'ഐഡി നമ്പർ',
    editPlaceholderDeposit: 'പ്രതീക്ഷിക്കുന്ന ആകെ തുക',
    editHintDeposit: 'വാടകക്കാരനിൽ നിന്ന് പ്രതീക്ഷിക്കുന്ന ആകെ തുക.',
    editPlaceholderPaid: '0',
    editPlaceholderName: 'വാടകക്കാരന്റെ മുഴുവൻ പേര്',
    editPlaceholderEmail: 'tenant@example.com',
    editPlaceholderPhone: 'വാടകക്കാരന്റെ ഫോൺ',
    editPlaceholderId: 'ആധാർ / സർക്കാർ ഐഡി നമ്പർ',
    editSavedTitle: 'സംരക്ഷിച്ചു',
    editSavedMsg: 'വാടകക്കാരന്റെ വിശദാംശങ്ങൾ അപ്ഡേറ്റ് ചെയ്തു.',
    editErr: 'അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയം. വീണ്ടും ശ്രമിക്കുക.',
    refundTitle: 'റീഫണ്ട് തീർത്തതായി അടയാളപ്പെടുത്തുക',
    refundFieldNote: 'കുറിപ്പ് (ഐച്ഛികം)',
    refundPlaceholderNote: 'ഈ റീഫണ്ടിനുള്ള ഐച്ഛിക കുറിപ്പ്…',
    refundConfirm: 'തീർത്തതായി അടയാളപ്പെടുത്തുക',
    refundAlertTitle: 'തീർത്തു',
    refundAlertMsg: 'റീഫണ്ട് തീർത്തതായി അടയാളപ്പെടുത്തി.',
    refundErr: 'റീഫണ്ട് തീർക്കുന്നതിൽ പരാജയം. വീണ്ടും ശ്രമിക്കുക.',
  },
  addTenant: {
    title: 'വാടകക്കാരനെ ചേർക്കുക',
    sub: 'വാടകക്കാരനെ ഒരു മുറിയിലേക്ക് നിയോഗിക്കുക',
    sectionRoom: '1. മുറി നിയോഗിക്കുക',
    sectionTenant: '2. വാടകക്കാരൻ',
    sectionDetails: '3. വാടക വിശദാംശങ്ങൾ',
    selectRoomPlaceholder: 'ഒഴിഞ്ഞ മുറി തിരഞ്ഞെടുക്കുക…',
    errRoomFull: 'ഈ മുറി നിറഞ്ഞു.',
    segmentExisting: 'നിലവിലുള്ള ഉപയോക്താവ്',
    segmentNew: 'പുതിയതായി സൃഷ്ടിക്കുക',
    selectUserPlaceholder: 'രജിസ്റ്റർ ചെയ്ത ഉപയോക്താവിനെ തിരഞ്ഞെടുക്കുക…',
    labelFullName: 'മുഴുവൻ പേര് *',
    labelEmail: 'ഇമെയിൽ *',
    placeholderName: 'വാടകക്കാരന്റെ പേര്',
    placeholderEmail: 'tenant@email.com',
    btnSendOtp: 'OTP അയയ്ക്കുക',
    labelOtp: 'OTP',
    placeholderOtp: '6-അക്ക',
    btnVerify: 'പരിശോധിക്കുക',
    verified: 'ഇമെയിൽ പരിശോധിച്ചു',
    labelPassword: 'താൽക്കാലിക പാസ്‌വേഡ് *',
    placeholderPassword: 'പാസ്‌വേഡ് സജ്ജമാക്കുക',
    passwordHint: 'കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ, വലിയ-ചെറിയ അക്ഷരം, സംഖ്യ, പ്രത്യേക അക്ഷരം (@$!%*?&) ആവശ്യം',
    btnAccountCreated: 'അക്കൗണ്ട് സൃഷ്ടിച്ചു',
    btnCreateAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    labelPhone: 'ഫോൺ *',
    placeholderPhone: 'വാടകക്കാരന്റെ ഫോൺ',
    labelIdNumber: 'ഐഡി നമ്പർ',
    placeholderIdNumber: 'ആധാർ / സർക്കാർ ഐഡി നമ്പർ',
    labelJoinDate: 'ചേർന്ന തീയതി *',
    placeholderJoinDate: 'തീയതി തിരഞ്ഞെടുക്കുക…',
    labelSecurityDeposit: 'സെക്യൂരിറ്റി ഡെപ്പോസിറ്റ് (₹)',
    labelAdvancePaid: 'അഡ്വാൻസ് അടച്ചു (₹)',
    labelNotes: 'കുറിപ്പുകൾ',
    placeholderNotes: 'ഐച്ഛിക കുറിപ്പ്',
    btnSubmit: 'വാടകക്കാരനെ ചേർക്കുക',
    alertRegisterTitle: 'രജിസ്ട്രേഷൻ പരാജയം',
    alertRegisterMsg: 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നതിൽ പരാജയം.',
    alertMissingTitle: 'വിശദാംശങ്ങൾ കാണുന്നില്ല',
    alertMissingName: 'ദയവായി വാടകക്കാരന്റെ പേര് നൽകുക.',
    alertInvalidNameTitle: 'അസാധുവായ പേര്',
    alertInvalidNameMsg: 'പേരിൽ കുറഞ്ഞത് 2 അക്ഷരങ്ങൾ ഉണ്ടായിരിക്കണം.',
    alertWeakPwTitle: 'ദുർബലമായ പാസ്‌വേഡ്',
    alertWeakPwMin: 'പാസ്‌വേഡിൽ കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ ഉണ്ടായിരിക്കണം.',
    alertWeakPwChars: 'പാസ്‌വേഡിൽ വലിയ-ചെറിയ അക്ഷരം, സംഖ്യ, പ്രത്യേക അക്ഷരം (@$!%*?&) ഉണ്ടായിരിക്കണം.',
    alertDone: 'ശരി',
    alertDoneMsg: 'വാടകക്കാരൻ വിജയകരമായി ചേർത്തു.',
    alertErr: 'വാടകക്കാരനെ ചേർക്കുന്നതിൽ പരാജയം.',
    selectRoomTitle: 'മുറി തിരഞ്ഞെടുക്കുക',
    selectUserTitle: 'ഉപയോക്താവിനെ തിരഞ്ഞെടുക്കുക',
    userAlreadyActive: 'ഇതിനകം സജീവ വാടകക്കാരൻ',
    selectDateTitle: 'ചേർന്ന തീയതി തിരഞ്ഞെടുക്കുക',
    occupancySuffix: '{{occupied}}/{{capacity}} താമസിച്ചു',
    rentPerMonth: '{{amount}}/മാസം',
  },
  payments: {
    title: 'പേയ്‌മെന്റുകൾ',
    headerSub: 'ഇന്ന് ശേഖരിച്ചത് ₹{{amount}}',
    stripOverdue: 'കാലഹരണപ്പെട്ടു',
    stripPending: 'തീർപ്പാക്കാത്തത്',
    stripCollected: 'ശേഖരിച്ചു',
    tabAll: 'എല്ലാം',
    tabOverdue: 'കാലഹരണപ്പെട്ടു',
    tabPending: 'തീർപ്പാക്കാത്തത്',
    tabPartial: 'ഭാഗികം',
    tabPaid: 'അടച്ചു',
    searchPlaceholder: 'വാടകക്കാരൻ, മുറി, മാസം എന്നിവയിൽ നിന്ന് തിരയുക…',
    emptyNoSearch: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    emptyNoRecords: '{{status}} രേഖകളൊന്നുമില്ല',
    statusPending: 'തീർപ്പാക്കാത്തത്',
    statusPartial: 'ഭാഗികം',
    statusOverdue: 'കാലഹരണപ്പെട്ടു',
    statusPaid: 'അടച്ചു',
    amountTotal: 'ആകെ',
    amountPaid: 'അടച്ചു',
    amountRemaining: 'ബാക്കി',
    proofAwaiting: 'പേയ്‌മെന്റ് രസീത് പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു',
    btnVerify: 'പരിശോധിക്കുക',
    btnReject: 'നിരസിക്കുക',
    verifyAlertTitle: 'പേയ്‌മെന്റ് പരിശോധിക്കുക',
    verifyAlertMsg: 'ഈ പേയ്‌മെന്റ് രസീത് പരിശോധിച്ച് വാടകക്കാരന് ക്രെഡിറ്റ് ചെയ്യണോ?',
    verifyAlertConfirm: 'പരിശോധിക്കുക',
    verifiedAlertTitle: 'പരിശോധിച്ചു',
    verifiedAlertMsg: 'പേയ്‌മെന്റ് പരിശോധിച്ച് ക്രെഡിറ്റ് ചെയ്തു.',
    rejectedAlertTitle: 'നിരസിച്ചു',
    rejectedAlertMsg: 'പേയ്‌മെന്റ് രസീത് നിരസിച്ചു. വാടകക്കാരനെ അറിയിക്കും.',
    errVerify: 'പരിശോധന പരാജയം.',
    errReject: 'നിരസിക്കൽ പരാജയം.',
    rejectModalTitle: 'പേയ്‌മെന്റ് നിരസിക്കുക',
    rejectModalSub: 'രസീത് എന്തുകൊണ്ട് നിരസിച്ചു എന്ന് വാടകക്കാരനെ അറിയിക്കാൻ കാരണം നൽകുക.',
    rejectPlaceholder: 'ഉദാ: മങ്ങിയ ചിത്രം, തെറ്റായ തുക…',
    btnCancel: 'റദ്ദാക്കുക',
  },
  approvals: {
    title: 'തീർപ്പാക്കാത്ത അംഗീകാരങ്ങൾ',
    count_one: '{{count}} പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു',
    count_other: '{{count}} പരിശോധനകൾക്കായി കാത്തിരിക്കുന്നു',
    allCaughtTitle: 'എല്ലാം പൂർത്തിയായി!',
    allCaughtSub: 'അംഗീകാരത്തിനായി പേയ്‌മെന്റ് രസീതുകളൊന്നും കാത്തിരിക്കുന്നില്ല.',
    btnApprove: 'അംഗീകരിക്കുക',
    btnReject: 'നിരസിക്കുക',
    rejectTitle: 'പേയ്‌മെന്റ് നിരസിക്കുക',
    rejectSub: 'രസീത് എന്തുകൊണ്ട് നിരസിച്ചു എന്ന് വാടകക്കാരനെ അറിയിക്കാൻ കാരണം നൽകുക.',
    rejectPlaceholder: 'ഉദാ: തെറ്റായ തുക, മങ്ങിയ ചിത്രം…',
    btnCancel: 'റദ്ദാക്കുക',
    errVerify: 'പരിശോധന പരാജയം.',
    errReject: 'നിരസിക്കൽ പരാജയം.',
  },
  transactions: {
    fallbackTitle: 'പേയ്‌മെന്റ്',
    totalCollected: 'ആകെ ശേഖരം',
    floatBanner: 'ഫ്ലോട്ടിംഗ് ബാക്ക്: {{amount}} മുന്നോട്ട് കൊണ്ടുപോകുന്നു',
    proofAwaiting: 'പേയ്‌മെന്റ് രസീത് പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു',
    sectionTransactions: 'ഇടപാടുകൾ',
    emptyTitle: 'ഇതുവരെ ഇടപാടുകളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',
    btnRecordPayment: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക',
    addPaymentTitle: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക',
    fieldAmount: 'തുക (₹) *',
    fieldMethod: 'പേയ്‌മെന്റ് രീതി *',
    methodCash: 'ക്യാഷ്',
    methodUpi: 'UPI',
    methodBank: 'ബാങ്ക്',
    methodCheque: 'ചെക്ക്',
    fieldDate: 'പേയ്‌മെന്റ് തീയതി *',
    placeholderDate: 'YYYY-MM-DD',
    fieldNotes: 'കുറിപ്പുകൾ',
    placeholderNotes: 'ഐച്ഛിക റഫറൻസ്',
    btnAttachProof: 'പേയ്‌മെന്റ് രസീത് ചേർക്കുക (ഐച്ഛികം)',
    btnCancel: 'റദ്ദാക്കുക',
    btnRecord: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുക',
    btnVerify: 'പരിശോധിക്കുക',
    btnReject: 'നിരസിക്കുക',
    btnReverse: 'ഈ പേയ്‌മെന്റ് റദ്ദാക്കുക',
    btnUndoReversal: 'റദ്ദാക്കൽ മാറ്റുക',
    refLabel: 'റഫ്: {{ref}}',
    recordedBy: '{{name}} ({{role}}) രേഖപ്പെടുത്തിയത്',
    alertPermissionTitle: 'അനുമതി',
    alertPermissionMsg: 'രസീത് ചേർക്കാൻ ഗാലറി അനുമതി ആവശ്യം.',
    alertErrRecord: 'പേയ്‌മെന്റ് രേഖപ്പെടുത്തുന്നതിൽ പരാജയം.',
    errVerify: 'പരിശോധന പരാജയം.',
    errReject: 'നിരസിക്കൽ പരാജയം.',
    errReverse: 'റദ്ദാക്കൽ പരാജയം.',
    errUndo: 'റദ്ദാക്കൽ മാറ്റുന്നതിൽ പരാജയം.',
    errLoad: 'പേയ്‌മെന്റ് വിശദാംശങ്ങൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല',
    btnRetry: 'വീണ്ടും ശ്രമിക്കുക',
    reversedAlertTitle: 'റദ്ദാക്കി',
    reversedAlertMsg: 'പേയ്‌മെന്റ് റദ്ദാക്കി.',
    undoneAlertTitle: 'മാറ്റി',
    undoneAlertMsg: 'റദ്ദാക്കൽ മാറ്റി. പേയ്‌മെന്റ് വീണ്ടും പ്രയോഗിച്ചു.',
    undoTitle: 'റദ്ദാക്കൽ മാറ്റുക',
    undoMsg: '{{amount}} ഈ രേഖയിലേക്ക് വീണ്ടും പ്രയോഗിക്കണോ?',
    undoConfirm: 'മാറ്റുക',
    reverseTitle: 'പേയ്‌മെന്റ് റദ്ദാക്കുക',
    reverseSub: '{{date}} ന് {{amount}} രേഖപ്പെടുത്തി',
    reversePlaceholder: 'റദ്ദാക്കലിനുള്ള കാരണം (ആവശ്യം)',
    reverseBtn: 'റദ്ദാക്കുക',
    btnCancel2: 'റദ്ദാക്കുക',
    statusCompleted: 'പൂർത്തിയായി',
    statusVerifying: 'പരിശോധനയിൽ',
    statusReversed: 'റദ്ദാക്കി',
    statusFailed: 'പരാജയം',
    floatMovedOut: 'ഫ്ലോട്ടിംഗ് തുക −{{amount}} ഈ മാസത്തിൽ നിന്ന് പുറത്ത്',
    floatMovedIn: 'ഫ്ലോട്ടിംഗ് തുക +{{amount}} ഈ മാസത്തിലേക്ക് കൊണ്ടുവന്നു',
  },
  complaints: {
    title: 'പരാതികൾ',
    count_one: '{{count}} പരാതി',
    count_other: '{{count}} പരാതികൾ',
    tabAll: 'എല്ലാം',
    tabOpen: 'തുറന്നത്',
    tabInProgress: 'പുരോഗതിയിൽ',
    tabResolved: 'പരിഹരിച്ചു',
    searchPlaceholder: 'തലക്കെട്ട് അല്ലെങ്കിൽ വാടകക്കാരനിൽ നിന്ന് തിരയുക…',
    emptyNoSearch: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
    emptyDefault: 'ഇവിടെ പരാതികളൊന്നുമില്ല',
    statusOpen: 'തുറന്നത്',
    statusInProgress: 'പുരോഗതിയിൽ',
    statusResolved: 'പരിഹരിച്ചു',
    statusRejected: 'നിരസിച്ചു',
    statusClosed: 'അടച്ചു',
    priorityLow: 'കുറഞ്ഞത്',
    priorityMedium: 'ഇടത്തരം',
    priorityHigh: 'ഉയർന്നത്',
    priorityUrgent: 'അടിയന്തരം',
    noLocation: 'സ്ഥലമില്ല',
  },
  complaintDetail: {
    title: 'പരാതി',
    errLoad: 'പരാതി ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല',
    btnRetry: 'വീണ്ടും ശ്രമിക്കുക',
    badgePrioritySuffix: '{{label}} മുൻഗണന',
    resolutionNotes: 'പരിഹാര കുറിപ്പുകൾ',
    sectionUpdateStatus: 'നില അപ്ഡേറ്റ് ചെയ്യുക',
    fieldResolutionNotes: 'പരിഹാര കുറിപ്പുകൾ *',
    placeholderResolution: 'പരിഹാരം ചുരുക്കമായി വിവരിക്കുക…',
    btnUpdateStatus: 'നില അപ്ഡേറ്റ് ചെയ്യുക',
    sectionComments: 'കുറിപ്പുകൾ',
    sectionCommentsCount: 'കുറിപ്പുകൾ ({{count}})',
    noComments: 'ഇതുവരെ കുറിപ്പുകളൊന്നുമില്ല. താഴെ സംഭാഷണം ആരംഭിക്കുക.',
    composerClosed: 'ഈ പരാതി അടച്ചു',
    composerReply: 'വാടകക്കാരന് മറുപടി നൽകുക…',
    statusInProgress: 'പുരോഗതിയിൽ',
    statusResolved: 'പരിഹരിച്ചു',
    statusRejected: 'നിരസിച്ചു',
  },
  expenses: {
    title: 'ചെലവുകൾ',
    add: 'ചേർക്കുക',
    addBtn: 'ചെലവ് ചേർക്കുക',
    headerSub: "{{month}} ഈ മാസത്തെ അറ്റ ലാഭം",
    allProperties: 'എല്ലാ സ്വത്തുക്കളും',
    netProfit: 'അറ്റ ലാഭം',
    rentCollected: 'ശേഖരിച്ച വാടക',
    totalExpenses: 'ആകെ ചെലവുകൾ',
    expenseCount: 'ചെലവുകളുടെ എണ്ണം',
    sectionRecurring: 'ആവർത്തന മാസികം',
    emptyRecurring: 'ആവർത്തന ചെലവുകളൊന്നും സജ്ജമാക്കിയിട്ടില്ല.',
    sectionExpenses: 'ചെലവുകൾ',
    emptyForMonth: '{{month}} ന് ചെലവുകളൊന്നുമില്ല.',
    emptyTapAdd: 'രേഖപ്പെടുത്താൻ ചേർക്കുക അമർത്തുക.',
    btnLogged: 'രേഖപ്പെടുത്തി',
    btnLogMonth: 'ഈ മാസം രേഖപ്പെടുത്തുക',
    tagMonthly: 'മാസികം',
    addExpenseTitle: 'ചെലവ് ചേർക്കുക',
    editExpenseTitle: 'ചെലവ് എഡിറ്റ് ചെയ്യുക',
    fieldProperty: 'സ്വത്ത് *',
    placeholderProperty: 'സ്വത്ത് തിരഞ്ഞെടുക്കുക…',
    selectPropertyTitle: 'സ്വത്ത് തിരഞ്ഞെടുക്കുക',
    fieldCategory: 'വിഭാഗം *',
    fieldTitle: 'തലക്കെട്ട്',
    placeholderTitle: 'ഉദാ: വാട്ടർ പമ്പ് റിപ്പയർ',
    fieldAmount: 'തുക *',
    placeholderAmount: '0',
    fieldMonth: 'മാസം',
    placeholderMonth: 'YYYY-MM',
    fieldExpenseDate: 'ചെലവ് തീയതി',
    placeholderExpenseDate: 'YYYY-MM-DD',
    fieldNotes: 'കുറിപ്പുകൾ',
    placeholderNotes: 'ഐച്ഛിക കുറിപ്പ്…',
    recurringTitle: 'ആവർത്തന മാസിക ചെലവ്',
    recurringSub: 'എല്ലാ മാസവും ഈ തുക സ്വയം രേഖപ്പെടുത്തുക',
    btnCancel: 'റദ്ദാക്കുക',
    btnSaveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    btnAddExpense: 'ചെലവ് ചേർക്കുക',
    catMaintenance: 'അറ്റകുറ്റപ്പണി',
    catElectricity: 'വൈദ്യുതി',
    catWater: 'വെള്ളം',
    catSociety: 'സൊസൈറ്റി',
    catRepairs: 'റിപ്പയർ',
    catCleaning: 'ക്ലീനിംഗ്',
    catInternet: 'ഇന്റർനെറ്റ്',
    catMisc: 'മറ്റുള്ളവ',
    alertOfflineSave: 'ഓഫ്‌ലൈൻ സംരക്ഷിച്ചു',
    alertOfflineSaveMsg: 'ചെലവ് ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ചു. ഓൺലൈൻ ആകുമ്പോൾ സ്വയം സിങ്ക് ചെയ്യും.',
    alertOfflineUpdateMsg: 'മാറ്റങ്ങൾ ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ചു. ഓൺലൈൻ ആകുമ്പോൾ സിങ്ക് ചെയ്യും.',
    alertOfflineDeleteTitle: 'ഓഫ്‌ലൈൻ ഇല്ലാതാക്കി',
    alertOfflineDeleteMsg: 'ചെലവ് ഈ ഉപകരണത്തിൽ നിന്ന് നീക്കം ചെയ്തു. ഓൺലൈൻ ആകുമ്പോൾ സ്വയം സിങ്ക് ചെയ്യും.',
    alertOfflineRecurMsg: 'ആവർത്തന ചെലവ് ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ചു. ഓൺലൈൻ ആകുമ്പോൾ സിങ്ക് ചെയ്യും.',
    alertOfflineRecurLogMsg: 'ഈ മാസത്തെ ആവർത്തന ചെലവ് ഈ ഉപകരണത്തിൽ ചേർത്തു. ഓൺലൈൻ ആകുമ്പോൾ സിങ്ക് ചെയ്യും.',
    alertAdded: 'ചേർത്തു',
    alertAddedMsg: 'ചെലവ് രേഖപ്പെടുത്തി.',
    alertUpdated: 'അപ്ഡേറ്റ് ചെയ്തു',
    alertUpdatedMsg: 'ചെലവ് അപ്ഡേറ്റ് ചെയ്തു.',
    alertDeleted: 'ഇല്ലാതാക്കി',
    alertDeletedMsg: 'ചെലവ് നീക്കം ചെയ്തു.',
    alertLogged: 'രേഖപ്പെടുത്തി',
    alertLoggedMsg: 'ഈ മാസത്തെ ആവർത്തന ചെലവ് ചേർത്തു.',
    errAdd: 'ചെലവ് ചേർക്കുന്നതിൽ പരാജയം.',
    errUpdate: 'ചെലവ് അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയം.',
    errDelete: 'ചെലവ് ഇല്ലാതാക്കുന്നതിൽ പരാജയം.',
    errLogRecur: 'ആവർത്തന ചെലവ് രേഖപ്പെടുത്തുന്നതിൽ പരാജയം.',
    deleteTitle: 'ചെലവ് ഇല്ലാതാക്കുക',
    deleteMsg: '"{{title}}" ({{amount}}) നീക്കം ചെയ്യണോ?',
    btnDelete: 'ഇല്ലാതാക്കുക',
    missingPropTitle: 'സ്വത്ത് കാണുന്നില്ല',
    missingPropMsg: 'ഈ ആവർത്തന ചെലവിന് സ്വത്തൊന്നുമില്ല. ദയവായി കൈയായി ചേർക്കുക.',
    alreadyLoggedTitle: 'ഇതിനകം രേഖപ്പെടുത്തി',
    alreadyLoggedMsg: 'ഈ ആവർത്തന ചെലവ് {{month}} ന് ഇതിനകം രേഖപ്പെടുത്തി.',
    expenseFallback: 'ചെലവ്',
    recurringFallback: 'ആവർത്തന ചെലവ്',
  },
  reports: {
    title: 'റിപ്പോർട്ടുകൾ',
    btnPdf: 'PDF',
    profitSummary: 'ലാഭ സംഗ്രഹം',
    rentCollected: 'ശേഖരിച്ച വാടക',
    expenses: 'ചെലവുകൾ',
    netProfit: 'അറ്റ ലാഭം',
    expenseRecorded: 'ഈ മാസം {{count}} ചെലവുകൾ രേഖപ്പെടുത്തി',
    sectionBreakdown: 'വരുമാന ചെലവ് വിശദാംശങ്ങൾ',
    totalIncome: 'ആകെ വരുമാനം',
    emptyExp: 'ഈ കാലയളവിൽ ചെലവുകളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',
    recurringSuffix: ' · ആവർത്തനം',
    errExport: 'റിപ്പോർട്ട് എക്സ്പോർട്ട് ചെയ്യാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
  },
  profile: {
    title: 'പ്രൊഫൈൽ',
    sub: 'പേയ്‌മെന്റ്, അക്കൗണ്ട് വിശദാംശങ്ങൾ കൈകാര്യം ചെയ്യുക',
    roleBadge: 'ഉടമ',
    sectionQr: 'പേയ്‌മെന്റ് QR കോഡ്',
    qrSub: 'വാടകക്കാർ ഈ QR സ്കാൻ ചെയ്ത് നിങ്ങൾക്ക് വാടക അടയ്ക്കും.',
    qrPlaceholder: 'QR ഇതുവരെ അപ്‌ലോഡ് ചെയ്തിട്ടില്ല',
    btnUploadQr: 'QR അപ്‌ലോഡ് / മാറ്റുക',
    sectionUpi: 'UPI പേയ്‌മെന്റ് വിശദാംശങ്ങൾ',
    fieldUpiId: 'UPI ഐഡി',
    fieldUpiName: 'രജിസ്റ്റർ ചെയ്ത പേര്',
    fieldUpiNumber: 'UPI നമ്പർ',
    btnSaveUpi: 'UPI വിശദാംശങ്ങൾ സംരക്ഷിക്കുക',
    sectionBank: 'ബാങ്ക് വിശദാംശങ്ങൾ',
    bankSub: 'റീഫണ്ടുകളും വാടക പേയ്‌മെന്റുകളും സ്വീകരിക്കാൻ.',
    fieldAccountHolder: 'അക്കൗണ്ട് ഉടമ',
    fieldAccountNumber: 'അക്കൗണ്ട് നമ്പർ',
    fieldBankName: 'ബാങ്ക് പേര്',
    fieldIfsc: 'IFSC കോഡ്',
    btnSaveBank: 'ബാങ്ക് വിശദാംശങ്ങൾ സംരക്ഷിക്കുക',
    sectionAccount: 'അക്കൗണ്ട്',
    btnSignOut: 'സൈൻ ഔട്ട്',
    alertSavedTitle: 'സംരക്ഷിച്ചു',
    alertSavedUpiMsg: 'UPI പേയ്‌മെന്റ് വിശദാംശങ്ങൾ അപ്ഡേറ്റ് ചെയ്തു.',
    alertSavedBankMsg: 'ബാങ്ക് വിശദാംശങ്ങൾ അപ്ഡേറ്റ് ചെയ്തു.',
    alertQrTitle: 'ശരി',
    alertQrMsg: 'പേയ്‌മെന്റ് QR കോഡ് അപ്ഡേറ്റ് ചെയ്തു. വാടകക്കാർക്ക് ഈ QR സ്കാൻ ചെയ്ത് അടയ്ക്കാം.',
    alertErrUpi: 'UPI വിശദാംശങ്ങൾ സംരക്ഷിക്കുന്നതിൽ പരാജയം.',
    alertErrBank: 'ബാങ്ക് വിശദാംശങ്ങൾ സംരക്ഷിക്കുന്നതിൽ പരാജയം.',
    alertErrQr: 'QR കോഡ് അപ്‌ലോഡ് ചെയ്യുന്നതിൽ പരാജയം.',
    alertPermissionTitle: 'അനുമതി',
    alertPermissionMsg: 'ഗാലറി അനുമതി ആവശ്യം.',
  },
  placeholder: {
    comingSoon: 'ഈ സ്ക്രീൻ ഉടൻ വരുന്നു.',
  },
};

function loadFile(lang) {
  const fp = path.join(__dirname, 'src', 'localization', 'translations', `${lang}.json`);
  let raw = fs.readFileSync(fp, 'utf8');
  let bom = false;
  if (raw.charCodeAt(0) === 0xFEFF) { bom = true; raw = raw.slice(1); }
  const data = JSON.parse(raw);
  return { fp, bom, data };
}

function deepMergeInto(target, source) {
  for (const key of Object.keys(source)) {
    const tv = target[key];
    const sv = source[key];
    const tvIsObj = tv !== null && typeof tv === 'object' && !Array.isArray(tv);
    const svIsObj = sv !== null && typeof sv === 'object' && !Array.isArray(sv);
    if (svIsObj && tvIsObj) {
      deepMergeInto(tv, sv);
    } else if (!(key in target) || (svIsObj && !tvIsObj)) {
      target[key] = sv;
    }
  }
  return target;
}

const { fp, bom, data } = loadFile('ml');
if (!data.owner) data.owner = {};
deepMergeInto(data.owner, ML);
const out = JSON.stringify(data, null, 2) + '\n';
fs.writeFileSync(fp, (bom ? '﻿' : '') + out, 'utf8');
console.log('✓ ml:', Object.keys(data.owner).filter(k => typeof data.owner[k] === 'object').length, 'nested keys');
