// One-shot script: adds Tamil translations for all owner portal keys.
const fs = require('fs');
const path = require('path');

const TA = {
  commonOwner: {
    saveChanges: 'மாற்றங்களை சேமி',
    remove: 'அகற்று',
    cancel: 'ரத்து',
    error: 'பிழை',
    verified: 'சரிபார்க்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    property: 'சொத்து',
    floor: 'தளம்',
    add: 'சேர்',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    yes: 'ஆம்',
    no: 'இல்லை',
    notes: 'குறிப்புகள்',
    room: 'அறை',
    months: 'மாதங்கள்',
  },
  drawer: {
    ownerDashboard: 'டாஷ்போர்டு',
    ownerProperties: 'சொத்துகள்',
    ownerTenants: 'வாடகைதாரர்கள்',
    ownerAddTenant: 'வாடகைதாரரைச் சேர்',
    ownerPayments: 'கட்டணங்கள்',
    ownerApprovals: 'நிலுவை ஒப்புதல்கள்',
    ownerComplaints: 'புகார்கள்',
    ownerExpenses: 'செலவுகள்',
    ownerReports: 'அறிக்கைகள்',
    ownerNotifications: 'அறிவிப்புகள்',
    helpCenter: 'உதவி மையம்',
    about: 'Happy Renting பற்றி',
    visitWebsite: 'வலைத்தளத்தைப் பார்வையிடு',
    rateApp: 'பயன்பாட்டை மதிப்பிடு',
    shareApp: 'Happy Renting பகிர்',
    shareMessage: 'Happy Renting மூலம் வாடகை, பில்கள் மற்றும் உங்கள் சொத்தை எளிதாக நிர்வகியுங்கள்! பயன்பாட்டைப் பதிவிறக்கு: https://play.google.com/store/apps/details?id=co.in.happyrenting.tenant',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    logout: 'வெளியேறு',
    logoutConfirmTitle: 'வெளியேறு',
    logoutConfirmMsg: 'நீங்கள் நிச்சயம் வெளியேற விரும்புகிறீர்களா?',
    shareErrorMsg: 'பயன்பாட்டு இணைப்பைப் பகிர முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    ownerWorkspace: 'உரிமையாளர் பணியிடம்',
    tenantWorkspace: 'வாடகைதாரர் பணியிடம்',
  },
  dashboard: {
    title: 'டாஷ்போர்டு',
    welcome: 'மீண்டும் வரவேற்கிறோம், {{name}}',
    totalCollected: 'மொத்த வசூல்',
    today: 'இன்று',
    overdue: 'காலாவதி',
    outstanding: 'நிலுவை',
    netCollectionMonth: 'இந்த மாத நிகர வசூல்',
    collected: 'வசூலிக்கப்பட்டது',
    expenses: 'செலவுகள்',
    entries: 'உள்ளீடுகள்',
    overview: 'மேலோட்டம்',
    properties: 'சொத்துகள்',
    rooms: 'அறைகள்',
    activeTenants: 'செயலில் உள்ள வாடகைதாரர்கள்',
    occupancy: 'ஆக்கிரமிப்பு',
    paidBills: 'செலுத்தப்பட்ட பில்கள்',
    overdueBills: 'காலாவதியான பில்கள்',
    paymentBreakdown: 'கட்டண விவரம்',
    pendingBills: 'நிலுவை பில்கள்',
    partialPayments: 'பகுதி கட்டணங்கள்',
    overdueBillsBreakdown: 'காலாவதியான பில்கள்',
    totalOutstanding: 'மொத்த நிலுவை',
    seeAll: 'அனைத்தும் பார்',
    loadError: 'பகுப்பாய்வை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்க கீழே இழுக்கவும்.',
  },
  properties: {
    title: 'சொத்துகள்',
    count_one: '{{count}} சொத்து',
    count_other: '{{count}} சொத்துகள்',
    add: 'சேர்',
    addBtn: 'சொத்தைச் சேர்',
    addTitle: 'சொத்தைச் சேர்',
    editTitle: 'சொத்தைத் திருத்து',
    fieldName: 'சொத்தின் பெயர் *',
    fieldAddress: 'முகவரி *',
    fieldCity: 'நகரம்',
    placeholderName: 'உதா: கிரீன் வேலி அடுக்குமாடி',
    placeholderAddress: 'தெரு, பகுதி, குறிப்பிடும் இடம்…',
    placeholderCity: 'உதா: சென்னை',
    cancel: 'ரத்து',
    save: 'மாற்றங்களை சேமி',
    saveAdd: 'சொத்தைச் சேர்',
    removeTitle: 'சொத்தை அகற்று',
    removeMsg: '"{{name}}" அகற்ற வேண்டுமா? இது சொத்தை செயலற்றதாக்கும். வாடகைதாரர் மற்றும் அறை தரவு பாதுகாக்கப்படும்.',
    errCreate: 'சொத்தை உருவாக்க முடியவில்லை.',
    errUpdate: 'சொத்தைப் புதுப்பிக்க முடியவில்லை.',
    errRemove: 'சொத்தை அகற்ற முடியவில்லை.',
    loading: 'சொத்துகள் ஏற்றப்படுகின்றன…',
    emptyTitle: 'இன்னும் சொத்துகள் இல்லை',
    emptyBody: 'முதல் சொத்தை உருவாக்க சேர் பொத்தானை அழுத்தவும்.',
    statsTotal: 'மொத்தம்',
    statsOccupied: 'ஆக்கிரமித்தது',
    statsVacant: 'காலி',
    statsOccupancy: 'ஆக்கிரமிப்பு',
    noRooms: 'இன்னும் அறைகள் இல்லை. அறைகளைச் சேர்க்க அட்டையை அழுத்தவும்.',
  },
  rooms: {
    title: 'அறைகள்',
    add: 'சேர்',
    addBtn: 'அறையைச் சேர்',
    addTitle: 'அறையைச் சேர்',
    editTitle: 'அறையைத் திருத்து',
    fieldRoomNumber: 'அறை எண் *',
    fieldFloor: 'தளம்',
    fieldCapacity: 'கொள்ளளவு *',
    fieldMonthlyRent: 'மாதாந்திர வாடகை (₹)',
    fieldSecurityDeposit: 'பாதுகாப்பு வைப்பு (₹)',
    fieldDescription: 'விவரம்',
    placeholderRoomNumber: 'உதா: 101',
    placeholderFloor: 'உதா: தரை',
    placeholderDescription: 'விருப்ப குறிப்பு',
    infoOccupied: '{{occupied}}/{{capacity}} ஆக்கிரமித்தது · கொள்ளளவை ஆக்கிரமிப்புக்கு கீழ் குறைக்க முடியாது',
    errCapacityMin: 'கொள்ளளவு குறைந்தது {{min}} ஆக இருக்க வேண்டும்',
    cancel: 'ரத்து',
    saveChanges: 'மாற்றங்களை சேமி',
    saveAdd: 'அறையைச் சேர்',
    removeTitle: 'அறையை அகற்று',
    removeMsg: 'அறை {{number}} அகற்ற வேண்டுமா? அறை காலியாக இருந்தால் இதை ரத்து செய்ய முடியாது.',
    errCreate: 'அறையை உருவாக்க முடியவில்லை.',
    errUpdate: 'அறையைப் புதுப்பிக்க முடியவில்லை.',
    errRemove: 'அறையை அகற்ற முடியவில்லை.',
    emptyTitle: 'இன்னும் அறைகள் இல்லை',
    emptySub: 'முதல் அறையை உருவாக்க சேரை அழுத்தவும்.',
    propertyFallback: 'சொத்து',
    count_one: '{{count}} அறை',
    count_other: '{{count}} அறைகள்',
    floorPrefix: '· தளம் {{floor}}',
    rent: 'வாடகை {{amount}}',
    deposit: 'வைப்பு {{amount}}',
    badgeFull: 'நிரம்பியது',
    badgeAvailable: 'கிடைக்கின்றது',
    occupiedCount: '{{occupied}}/{{capacity}} ஆக்கிரமித்தது',
  },
  tenants: {
    title: 'வாடகைதாரர்கள்',
    add: 'சேர்',
    addBtn: 'வாடகைதாரரைச் சேர்',
    count_one: '{{count}} மொத்தம்',
    count_other: '{{count}} மொத்தம்',
    countActive_one: '{{count}} செயலில்',
    countActive_other: '{{count}} செயலில்',
    countVacated_one: '{{count}} காலி செய்தவர்',
    countVacated_other: '{{count}} காலி செய்தவர்',
    tabActive: 'செயலில்',
    tabVacated: 'காலி செய்தவர்',
    tabAll: 'அனைத்தும்',
    searchPlaceholder: 'பெயர், அறை, சொத்து மூலம் தேடு…',
    emptyNoSearch: 'முடிவுகள் எதுவும் கிடைக்கவில்லை',
    emptyNoTenants: 'வாடகைதாரர்கள் இல்லை',
    emptyNoActive: 'செயலில் உள்ள வாடகைதாரர்கள் இல்லை',
    emptyNoVacated: 'காலி செய்த வாடகைதாரர்கள் இல்லை',
    detailRoom: 'அறை',
    detailProperty: 'சொத்து',
    detailMonthlyRent: 'மாதாந்திர வாடகை',
    detailMoveIn: 'சேர்ந்த தேதி',
    detailExit: 'வெளியேறும் தேதி',
    detailPhone: 'தொலைபேசி',
    detailIdNumber: 'அடையாள எண்',
    detailSecurityDeposit: 'பாதுகாப்பு வைப்பு',
    detailAdvancePaid: 'முன்பணம் செலுத்தப்பட்டது',
    detailNotes: 'குறிப்புகள்',
    detailEdit: 'விவரங்களைத் திருத்து',
    detailMoveOut: 'வாடகைதாரரை காலி செய்',
    detailReverse: 'காலி செய்தலை மாற்று',
    refundDue: 'பணத்திருப்பம் நிலுவை',
    refundSettled: 'பணத்திருப்பம் தீர்க்கப்பட்டது',
    markSettled: 'தீர்க்கப்பட்டதாக குறி',
    statusActive: 'செயலில்',
    statusVacated: 'காலி செய்தனர்',
    statusPendingDeletion: 'நீக்க நிலுவை',
    since: '{{date}} முதல்',
    moveOutTitle: 'வாடகைதாரரை காலி செய்',
    moveOutFieldExitDate: 'வெளியேறும் தேதி *',
    moveOutFieldNotes: 'குறிப்புகள் (விருப்பம்)',
    moveOutPlaceholderNotes: 'காலி செய்ய காரணம்…',
    moveOutConfirm: 'காலி செய்தலை உறுதிப்படுத்து',
    moveOutAlertTitle: 'சரி',
    moveOutAlertMsg: 'வாடகைதாரர் வெற்றிகரமாக காலி செய்யப்பட்டார்.',
    moveOutErr: 'காலி செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    moveOutEmptyExitDate: 'வெளியேறும் தேதி',
    reverseAlertTitle: 'காலி செய்தலை மாற்று',
    reverseAlertMsg: '{{name}} (அறை {{room}}) மீண்டும் செயலில் மாற்ற வேண்டுமா? இது அறையை மீண்டும் ஆக்கிரமிக்கச் செய்யும்.',
    reverseAlertRestore: 'மீட்டமை',
    reverseDeletedTitle: 'காலி செய்தலை மாற்ற இயலாது',
    reverseDeletedMsg: 'இந்த வாடகைதாரர் கணக்கு நீக்கப்பட்டது. காலி செய்தலை மாற்ற இயலாது.',
    reverseOk: 'சரி',
    reverseDoneTitle: 'மாற்றப்பட்டது',
    reverseDoneMsg: 'வாடகைதாரர் செயல் நிலைக்கு மீட்டமைக்கப்பட்டார்.',
    reverseErr: 'மாற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    editTitle: 'வாடகைதாரரைத் திருத்து',
    editTabFinance: 'நிதி',
    editTabProfile: 'சுயவிவரம்',
    editErrAdvanceDeposit: 'முன்பணம் பாதுகாப்பு வைப்புக்கு கீழ் அல்லது சமமாக இருக்க வேண்டும்.',
    editFieldTargetDeposit: 'இலக்கு பாதுகாப்பு வைப்பு (மொத்த ₹)',
    editFieldPaid: 'தற்போது செலுத்தியது (₹)',
    editFieldFullName: 'முழுப் பெயர்',
    editFieldEmail: 'மின்னஞ்சல்',
    editFieldPhone: 'தொலைபேசி',
    editFieldIdNumber: 'அடையாள எண்',
    editPlaceholderDeposit: 'எதிர்பார்க்கும் மொத்த தொகை',
    editHintDeposit: 'வாடகைதாரரிடம் இருந்து எதிர்பார்க்கும் மொத்த தொகை.',
    editPlaceholderPaid: '0',
    editPlaceholderName: 'வாடகைதாரரின் முழுப் பெயர்',
    editPlaceholderEmail: 'tenant@example.com',
    editPlaceholderPhone: 'வாடகைதாரரின் தொலைபேசி',
    editPlaceholderId: 'ஆதார் / அரசு அடையாள எண்',
    editSavedTitle: 'சேமிக்கப்பட்டது',
    editSavedMsg: 'வாடகைதாரர் விவரங்கள் புதுப்பிக்கப்பட்டன.',
    editErr: 'புதுப்பிப்பு முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    refundTitle: 'பணத்திருப்பம் தீர்க்கப்பட்டதாக குறி',
    refundFieldNote: 'குறிப்பு (விருப்பம்)',
    refundPlaceholderNote: 'இந்தப் பணத்திருப்பத்திற்கான விருப்பக் குறிப்பு…',
    refundConfirm: 'தீர்க்கப்பட்டதாக குறி',
    refundAlertTitle: 'தீர்க்கப்பட்டது',
    refundAlertMsg: 'பணத்திருப்பம் தீர்க்கப்பட்டதாக குறிக்கப்பட்டது.',
    refundErr: 'பணத்திருப்பத்தை தீர்க்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  },
  addTenant: {
    title: 'வாடகைதாரரைச் சேர்',
    sub: 'வாடகைதாரரை ஒரு அறைக்கு நியமி',
    sectionRoom: '1. அறையை நியமி',
    sectionTenant: '2. வாடகைதாரர்',
    sectionDetails: '3. வாடகை விவரங்கள்',
    selectRoomPlaceholder: 'காலி அறையைத் தேர்ந்தெடு…',
    errRoomFull: 'இந்த அறை நிரம்பியது.',
    segmentExisting: 'ஏற்கனவே உள்ள பயனர்',
    segmentNew: 'புதிதாக உருவாக்கு',
    selectUserPlaceholder: 'பதிவுசெய்த பயனரைத் தேர்ந்தெடு…',
    labelFullName: 'முழுப் பெயர் *',
    labelEmail: 'மின்னஞ்சல் *',
    placeholderName: 'வாடகைதாரரின் பெயர்',
    placeholderEmail: 'tenant@email.com',
    btnSendOtp: 'OTP அனுப்பு',
    labelOtp: 'OTP',
    placeholderOtp: '6-இலக்க',
    btnVerify: 'சரிபார்',
    verified: 'மின்னஞ்சல் சரிபார்க்கப்பட்டது',
    labelPassword: 'தற்காலிக கடவுச்சொல் *',
    placeholderPassword: 'கடவுச்சொல்லை அமை',
    passwordHint: 'குறைந்தது 8 எழுத்துக்கள், பெரிய-சிறிய எழுத்து, எண், சிறப்பு எழுத்து (@$!%*?&) தேவை',
    btnAccountCreated: 'கணக்கு உருவாக்கப்பட்டது',
    btnCreateAccount: 'கணக்கை உருவாக்கு',
    labelPhone: 'தொலைபேசி *',
    placeholderPhone: 'வாடகைதாரரின் தொலைபேசி',
    labelIdNumber: 'அடையாள எண்',
    placeholderIdNumber: 'ஆதார் / அரசு அடையாள எண்',
    labelJoinDate: 'சேர்ந்த தேதி *',
    placeholderJoinDate: 'தேதியைத் தேர்ந்தெடு…',
    labelSecurityDeposit: 'பாதுகாப்பு வைப்பு (₹)',
    labelAdvancePaid: 'முன்பணம் செலுத்தியது (₹)',
    labelNotes: 'குறிப்புகள்',
    placeholderNotes: 'விருப்பக் குறிப்பு',
    btnSubmit: 'வாடகைதாரரைச் சேர்',
    alertRegisterTitle: 'பதிவு முடியவில்லை',
    alertRegisterMsg: 'கணக்கை உருவாக்க முடியவில்லை.',
    alertMissingTitle: 'விவரங்கள் இல்லை',
    alertMissingName: 'தயவுசெய்து வாடகைதாரரின் பெயரை உள்ளிடவும்.',
    alertInvalidNameTitle: 'தவறான பெயர்',
    alertInvalidNameMsg: 'பெயரில் குறைந்தது 2 எழுத்துக்கள் இருக்க வேண்டும்.',
    alertWeakPwTitle: 'பலவீனமான கடவுச்சொல்',
    alertWeakPwMin: 'கடவுச்சொல்லில் குறைந்தது 8 எழுத்துக்கள் இருக்க வேண்டும்.',
    alertWeakPwChars: 'கடவுச்சொல்லில் பெரிய-சிறிய எழுத்து, எண், சிறப்பு எழுத்து (@$!%*?&) இருக்க வேண்டும்.',
    alertDone: 'சரி',
    alertDoneMsg: 'வாடகைதாரர் வெற்றிகரமாக சேர்க்கப்பட்டார்.',
    alertErr: 'வாடகைதாரரைச் சேர்க்க முடியவில்லை.',
    selectRoomTitle: 'அறையைத் தேர்ந்தெடு',
    selectUserTitle: 'பயனரைத் தேர்ந்தெடு',
    userAlreadyActive: 'ஏற்கனவே செயலில் உள்ள வாடகைதாரர்',
    selectDateTitle: 'சேர்ந்த தேதியைத் தேர்ந்தெடு',
    occupancySuffix: '{{occupied}}/{{capacity}} ஆக்கிரமித்தது',
    rentPerMonth: '{{amount}}/மாதம்',
  },
  payments: {
    title: 'கட்டணங்கள்',
    headerSub: 'இன்று வசூலித்தது ₹{{amount}}',
    stripOverdue: 'காலாவதி',
    stripPending: 'நிலுவை',
    stripCollected: 'வசூலிக்கப்பட்டது',
    tabAll: 'அனைத்தும்',
    tabOverdue: 'காலாவதி',
    tabPending: 'நிலுவை',
    tabPartial: 'பகுதி',
    tabPaid: 'செலுத்தப்பட்டது',
    searchPlaceholder: 'வாடகைதாரர், அறை, மாதம் மூலம் தேடு…',
    emptyNoSearch: 'முடிவுகள் எதுவும் கிடைக்கவில்லை',
    emptyNoRecords: '{{status}} பதிவுகள் இல்லை',
    statusPending: 'நிலுவை',
    statusPartial: 'பகுதி',
    statusOverdue: 'காலாவதி',
    statusPaid: 'செலுத்தப்பட்டது',
    amountTotal: 'மொத்தம்',
    amountPaid: 'செலுத்தப்பட்டது',
    amountRemaining: 'மீதமுள்ளது',
    proofAwaiting: 'கட்டண ஆதாரம் சரிபார்ப்புக்காக காத்திருக்கிறது',
    btnVerify: 'சரிபார்',
    btnReject: 'நிராகரி',
    verifyAlertTitle: 'கட்டணத்தை சரிபார்',
    verifyAlertMsg: 'இந்த கட்டண ஆதாரத்தை சரிபார்த்து வாடகைதாரருக்கு வரவு வைக்கவா?',
    verifyAlertConfirm: 'சரிபார்',
    verifiedAlertTitle: 'சரிபார்க்கப்பட்டது',
    verifiedAlertMsg: 'கட்டணம் சரிபார்க்கப்பட்டு வரவு வைக்கப்பட்டது.',
    rejectedAlertTitle: 'நிராகரிக்கப்பட்டது',
    rejectedAlertMsg: 'கட்டண ஆதாரம் நிராகரிக்கப்பட்டது. வாடகைதாரருக்கு அறிவிக்கப்படும்.',
    errVerify: 'சரிபார்ப்பு முடியவில்லை.',
    errReject: 'நிராகரிப்பு முடியவில்லை.',
    rejectModalTitle: 'கட்டணத்தை நிராகரி',
    rejectModalSub: 'ஆதாரம் ஏன் நிராகரிக்கப்பட்டது என்பதை வாடகைதாரருக்கு தெரிவிக்க காரணம் கொடு.',
    rejectPlaceholder: 'உதா: மங்கலான படம், தவறான தொகை…',
    btnCancel: 'ரத்து',
  },
  approvals: {
    title: 'நிலுவை ஒப்புதல்கள்',
    count_one: '{{count}} சரிபார்ப்புக்காக காத்திருக்கிறது',
    count_other: '{{count}} சரிபார்ப்புகளுக்காக காத்திருக்கிறது',
    allCaughtTitle: 'அனைத்தும் முடிந்தது!',
    allCaughtSub: 'ஒப்புதலுக்காக கட்டண ஆதாரங்கள் எதுவும் காத்திருக்கவில்லை.',
    btnApprove: 'ஒப்பு',
    btnReject: 'நிராகரி',
    rejectTitle: 'கட்டணத்தை நிராகரி',
    rejectSub: 'ஆதாரம் ஏன் நிராகரிக்கப்பட்டது என்பதை வாடகைதாரருக்கு தெரிவிக்க காரணம் கொடு.',
    rejectPlaceholder: 'உதா: தவறான தொகை, மங்கலான படம்…',
    btnCancel: 'ரத்து',
    errVerify: 'சரிபார்ப்பு முடியவில்லை.',
    errReject: 'நிராகரிப்பு முடியவில்லை.',
  },
  transactions: {
    fallbackTitle: 'கட்டணம்',
    totalCollected: 'மொத்த வசூல்',
    floatBanner: 'மிதக்கும் நிலுவை: {{amount}} முன்னோக்கி கொண்டு செல்லப்படுகிறது',
    proofAwaiting: 'கட்டண ஆதாரம் சரிபார்ப்புக்காக காத்திருக்கிறது',
    sectionTransactions: 'பரிவர்த்தனைகள்',
    emptyTitle: 'இன்னும் பரிவர்த்தனைகள் பதிவு செய்யப்படவில்லை.',
    btnRecordPayment: 'கட்டணத்தைப் பதிவு செய்',
    addPaymentTitle: 'கட்டணத்தைப் பதிவு செய்',
    fieldAmount: 'தொகை (₹) *',
    fieldMethod: 'கட்டண முறை *',
    methodCash: 'பணம்',
    methodUpi: 'UPI',
    methodBank: 'வங்கி',
    methodCheque: 'காசோலை',
    fieldDate: 'கட்டண தேதி *',
    placeholderDate: 'YYYY-MM-DD',
    fieldNotes: 'குறிப்புகள்',
    placeholderNotes: 'விருப்ப குறிப்பு',
    btnAttachProof: 'கட்டண ஆதாரத்தை இணை (விருப்பம்)',
    btnCancel: 'ரத்து',
    btnRecord: 'கட்டணத்தைப் பதிவு செய்',
    btnVerify: 'சரிபார்',
    btnReject: 'நிராகரி',
    btnReverse: 'இந்த கட்டணத்தை ரத்து செய்',
    btnUndoReversal: 'ரத்து செய்தலை மாற்று',
    refLabel: 'குறி: {{ref}}',
    recordedBy: '{{name}} ({{role}}) பதிவு செய்தார்',
    alertPermissionTitle: 'அனுமதி',
    alertPermissionMsg: 'ஆதாரத்தை இணைக்க கேலரி அனுமதி தேவை.',
    alertErrRecord: 'கட்டணத்தைப் பதிவு செய்ய முடியவில்லை.',
    errVerify: 'சரிபார்ப்பு முடியவில்லை.',
    errReject: 'நிராகரிப்பு முடியவில்லை.',
    errReverse: 'ரத்து முடியவில்லை.',
    errUndo: 'ரத்து செய்தலை மாற்ற முடியவில்லை.',
    errLoad: 'கட்டண விவரங்களை ஏற்ற முடியவில்லை',
    btnRetry: 'மீண்டும் முயற்சி',
    reversedAlertTitle: 'ரத்து செய்யப்பட்டது',
    reversedAlertMsg: 'கட்டணம் ரத்து செய்யப்பட்டது.',
    undoneAlertTitle: 'மாற்றப்பட்டது',
    undoneAlertMsg: 'ரத்து செய்தல் மாற்றப்பட்டது. கட்டணம் மீண்டும் பயன்படுத்தப்பட்டது.',
    undoTitle: 'ரத்து செய்தலை மாற்று',
    undoMsg: '{{amount}} இந்தப் பதிவுக்கு மீண்டும் பயன்படுத்தவா?',
    undoConfirm: 'மாற்று',
    reverseTitle: 'கட்டணத்தை ரத்து செய்',
    reverseSub: '{{date}} அன்று {{amount}} பதிவு செய்யப்பட்டது',
    reversePlaceholder: 'ரத்து செய்வதற்கான காரணம் (தேவை)',
    reverseBtn: 'ரத்து செய்',
    btnCancel2: 'ரத்து',
    statusCompleted: 'நிறைவு',
    statusVerifying: 'சரிபார்க்கிறது',
    statusReversed: 'ரத்து செய்யப்பட்டது',
    statusFailed: 'தோல்வி',
    floatMovedOut: 'மிதக்கும் தொகை −{{amount}} இந்த மாதத்திலிருந்து வெளியே',
    floatMovedIn: 'மிதக்கும் தொகை +{{amount}} இந்த மாதத்திற்கு கொண்டு வரப்பட்டது',
  },
  complaints: {
    title: 'புகார்கள்',
    count_one: '{{count}} புகார்',
    count_other: '{{count}} புகார்கள்',
    tabAll: 'அனைத்தும்',
    tabOpen: 'திறந்தது',
    tabInProgress: 'முன்னேற்றத்தில்',
    tabResolved: 'தீர்க்கப்பட்டது',
    searchPlaceholder: 'தலைப்பு அல்லது வாடகைதாரர் மூலம் தேடு…',
    emptyNoSearch: 'முடிவுகள் எதுவும் கிடைக்கவில்லை',
    emptyDefault: 'இங்கு புகார்கள் எதுவும் இல்லை',
    statusOpen: 'திறந்தது',
    statusInProgress: 'முன்னேற்றத்தில்',
    statusResolved: 'தீர்க்கப்பட்டது',
    statusRejected: 'நிராகரிக்கப்பட்டது',
    statusClosed: 'மூடப்பட்டது',
    priorityLow: 'குறைவு',
    priorityMedium: 'நடுத்தர',
    priorityHigh: 'உயர்',
    priorityUrgent: 'அவசர',
    noLocation: 'இடம் இல்லை',
  },
  complaintDetail: {
    title: 'புகார்',
    errLoad: 'புகாரை ஏற்ற முடியவில்லை',
    btnRetry: 'மீண்டும் முயற்சி',
    badgePrioritySuffix: '{{label}} முன்னுரிமை',
    resolutionNotes: 'தீர்வு குறிப்புகள்',
    sectionUpdateStatus: 'நிலையை புதுப்பி',
    fieldResolutionNotes: 'தீர்வு குறிப்புகள் *',
    placeholderResolution: 'தீர்வை சுருக்கமாக விவரி…',
    btnUpdateStatus: 'நிலையை புதுப்பி',
    sectionComments: 'குறிப்புகள்',
    sectionCommentsCount: 'குறிப்புகள் ({{count}})',
    noComments: 'இன்னும் குறிப்புகள் இல்லை. கீழே உரையாடலைத் தொடங்கு.',
    composerClosed: 'இந்தப் புகார் மூடப்பட்டது',
    composerReply: 'வாடகைதாரருக்கு பதிலளி…',
    statusInProgress: 'முன்னேற்றத்தில்',
    statusResolved: 'தீர்க்கப்பட்டது',
    statusRejected: 'நிராகரிக்கப்பட்டது',
  },
  expenses: {
    title: 'செலவுகள்',
    add: 'சேர்',
    addBtn: 'செலவைச் சேர்',
    headerSub: "{{month}} இந்த மாத நிகர லாபம்",
    allProperties: 'அனைத்து சொத்துகள்',
    netProfit: 'நிகர லாபம்',
    rentCollected: 'வசூலிக்கப்பட்ட வாடகை',
    totalExpenses: 'மொத்த செலவுகள்',
    expenseCount: 'செலவுகளின் எண்ணிக்கை',
    sectionRecurring: 'தொடர்ச்சியான மாதாந்திர',
    emptyRecurring: 'தொடர்ச்சியான செலவுகள் எதுவும் அமைக்கப்படவில்லை.',
    sectionExpenses: 'செலவுகள்',
    emptyForMonth: '{{month}} க்கு செலவுகள் இல்லை.',
    emptyTapAdd: 'பதிவு செய்ய சேரை அழுத்தவும்.',
    btnLogged: 'பதிவு செய்யப்பட்டது',
    btnLogMonth: 'இந்த மாதத்தைப் பதிவு செய்',
    tagMonthly: 'மாதாந்திர',
    addExpenseTitle: 'செலவைச் சேர்',
    editExpenseTitle: 'செலவைத் திருத்து',
    fieldProperty: 'சொத்து *',
    placeholderProperty: 'சொத்தைத் தேர்ந்தெடு…',
    selectPropertyTitle: 'சொத்தைத் தேர்ந்தெடு',
    fieldCategory: 'வகை *',
    fieldTitle: 'தலைப்பு',
    placeholderTitle: 'உதா: நீர் பம்ப் பழுது',
    fieldAmount: 'தொகை *',
    placeholderAmount: '0',
    fieldMonth: 'மாதம்',
    placeholderMonth: 'YYYY-MM',
    fieldExpenseDate: 'செலவு தேதி',
    placeholderExpenseDate: 'YYYY-MM-DD',
    fieldNotes: 'குறிப்புகள்',
    placeholderNotes: 'விருப்பக் குறிப்பு…',
    recurringTitle: 'தொடர்ச்சியான மாதாந்திர செலவு',
    recurringSub: 'ஒவ்வொரு மாதமும் இந்தத் தொகை தானாகப் பதிவு செய்யப்படும்',
    btnCancel: 'ரத்து',
    btnSaveChanges: 'மாற்றங்களை சேமி',
    btnAddExpense: 'செலவைச் சேர்',
    catMaintenance: 'பராமரிப்பு',
    catElectricity: 'மின்சாரம்',
    catWater: 'நீர்',
    catSociety: 'சங்கம்',
    catRepairs: 'பழுதுபார்ப்பு',
    catCleaning: 'சுத்தம்',
    catInternet: 'இணையம்',
    catMisc: 'பிற',
    alertOfflineSave: 'ஆஃப்லைனில் சேமிக்கப்பட்டது',
    alertOfflineSaveMsg: 'செலவு இந்த சாதனத்தில் சேமிக்கப்பட்டது. ஆன்லைனில் இணைக்கும்போது தானாக ஒத்திசைக்கும்.',
    alertOfflineUpdateMsg: 'மாற்றங்கள் இந்த சாதனத்தில் சேமிக்கப்பட்டன. ஆன்லைனில் இணைக்கும்போது ஒத்திசைக்கும்.',
    alertOfflineDeleteTitle: 'ஆஃப்லைனில் நீக்கப்பட்டது',
    alertOfflineDeleteMsg: 'செலவு இந்த சாதனத்திலிருந்து அகற்றப்பட்டது. ஆன்லைனில் இணைக்கும்போது தானாக ஒத்திசைக்கும்.',
    alertOfflineRecurMsg: 'தொடர்ச்சியான செலவு இந்த சாதனத்தில் சேமிக்கப்பட்டது. ஆன்லைனில் இணைக்கும்போது ஒத்திசைக்கும்.',
    alertOfflineRecurLogMsg: 'இந்த மாதத்தின் தொடர்ச்சியான செலவு இந்த சாதனத்தில் சேர்க்கப்பட்டது. ஆன்லைனில் இணைக்கும்போது ஒத்திசைக்கும்.',
    alertAdded: 'சேர்க்கப்பட்டது',
    alertAddedMsg: 'செலவு பதிவு செய்யப்பட்டது.',
    alertUpdated: 'புதுப்பிக்கப்பட்டது',
    alertUpdatedMsg: 'செலவு புதுப்பிக்கப்பட்டது.',
    alertDeleted: 'நீக்கப்பட்டது',
    alertDeletedMsg: 'செலவு அகற்றப்பட்டது.',
    alertLogged: 'பதிவு செய்யப்பட்டது',
    alertLoggedMsg: 'இந்த மாதத்தின் தொடர்ச்சியான செலவு சேர்க்கப்பட்டது.',
    errAdd: 'செலவைச் சேர்க்க முடியவில்லை.',
    errUpdate: 'செலவைப் புதுப்பிக்க முடியவில்லை.',
    errDelete: 'செலவை நீக்க முடியவில்லை.',
    errLogRecur: 'தொடர்ச்சியான செலவைப் பதிவு செய்ய முடியவில்லை.',
    deleteTitle: 'செலவை நீக்கு',
    deleteMsg: '"{{title}}" ({{amount}}) அகற்றவா?',
    btnDelete: 'நீக்கு',
    missingPropTitle: 'சொத்து இல்லை',
    missingPropMsg: 'இந்த தொடர்ச்சியான செலவுக்கு சொத்து இல்லை. தயவுசெய்து கைமுறையாக சேர்க்கவும்.',
    alreadyLoggedTitle: 'ஏற்கனவே பதிவு செய்யப்பட்டது',
    alreadyLoggedMsg: 'இந்த தொடர்ச்சியான செலவு {{month}} க்கு ஏற்கனவே பதிவு செய்யப்பட்டது.',
    expenseFallback: 'செலவு',
    recurringFallback: 'தொடர்ச்சியான செலவு',
  },
  reports: {
    title: 'அறிக்கைகள்',
    btnPdf: 'PDF',
    profitSummary: 'லாப சுருக்கம்',
    rentCollected: 'வசூலிக்கப்பட்ட வாடகை',
    expenses: 'செலவுகள்',
    netProfit: 'நிகர லாபம்',
    expenseRecorded: 'இந்த மாதம் {{count}} செலவுகள் பதிவு செய்யப்பட்டன',
    sectionBreakdown: 'வருமான செலவு விவரம்',
    totalIncome: 'மொத்த வருமானம்',
    emptyExp: 'இந்த காலகட்டத்தில் செலவுகள் எதுவும் பதிவு செய்யப்படவில்லை.',
    recurringSuffix: ' · தொடர்ச்சியான',
    errExport: 'அறிக்கையை ஏற்றுமதி செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  },
  profile: {
    title: 'சுயவிவரம்',
    sub: 'கட்டணம் மற்றும் கணக்கு விவரங்களை நிர்வகி',
    roleBadge: 'உரிமையாளர்',
    sectionQr: 'கட்டண QR குறியீடு',
    qrSub: 'வாடகைதாரர்கள் இந்த QR ஐ ஸ்கேன் செய்து உங்களுக்கு வாடகை செலுத்துவார்கள்.',
    qrPlaceholder: 'QR இன்னும் பதிவேற்றப்படவில்லை',
    btnUploadQr: 'QR ஐ பதிவேற்று / மாற்று',
    sectionUpi: 'UPI கட்டண விவரங்கள்',
    fieldUpiId: 'UPI ஐடி',
    fieldUpiName: 'பதிவுசெய்த பெயர்',
    fieldUpiNumber: 'UPI எண்',
    btnSaveUpi: 'UPI விவரங்களை சேமி',
    sectionBank: 'வங்கி விவரங்கள்',
    bankSub: 'பணத்திருப்பம் மற்றும் வாடகை கட்டணங்களைப் பெற.',
    fieldAccountHolder: 'கணக்கு உரிமையாளர்',
    fieldAccountNumber: 'கணக்கு எண்',
    fieldBankName: 'வங்கியின் பெயர்',
    fieldIfsc: 'IFSC குறியீடு',
    btnSaveBank: 'வங்கி விவரங்களை சேமி',
    sectionAccount: 'கணக்கு',
    btnSignOut: 'வெளியேறு',
    alertSavedTitle: 'சேமிக்கப்பட்டது',
    alertSavedUpiMsg: 'UPI கட்டண விவரங்கள் புதுப்பிக்கப்பட்டன.',
    alertSavedBankMsg: 'வங்கி விவரங்கள் புதுப்பிக்கப்பட்டன.',
    alertQrTitle: 'சரி',
    alertQrMsg: 'கட்டண QR குறியீடு புதுப்பிக்கப்பட்டது. வாடகைதாரர்கள் இப்போது இந்த QR ஐ ஸ்கேன் செய்து செலுத்தலாம்.',
    alertErrUpi: 'UPI விவரங்களை சேமிக்க முடியவில்லை.',
    alertErrBank: 'வங்கி விவரங்களை சேமிக்க முடியவில்லை.',
    alertErrQr: 'QR குறியீட்டைப் பதிவேற்ற முடியவில்லை.',
    alertPermissionTitle: 'அனுமதி',
    alertPermissionMsg: 'கேலரி அனுமதி தேவை.',
  },
  placeholder: {
    comingSoon: 'இந்தத் திரை விரைவில் வருகிறது.',
  },
};

function loadFile(lang) {
  const fp = path.join(__dirname, 'src', 'localization', 'translations', `${lang}.json`);
  let raw = fs.readFileSync(fp, 'utf8');
  let bom = false;
  if (raw.charCodeAt(0) === 0xFEFF) { bom = true; raw = raw.slice(1); }
  const data = JSON.parse(raw);
  return { fp, bom, data };
}

function deepMergeInto(target, source) {
  for (const key of Object.keys(source)) {
    const tv = target[key];
    const sv = source[key];
    const tvIsObj = tv !== null && typeof tv === 'object' && !Array.isArray(tv);
    const svIsObj = sv !== null && typeof sv === 'object' && !Array.isArray(sv);
    if (svIsObj && tvIsObj) {
      deepMergeInto(tv, sv);
    } else if (!(key in target) || (svIsObj && !tvIsObj)) {
      target[key] = sv;
    }
  }
  return target;
}

const { fp, bom, data } = loadFile('ta');
if (!data.owner) data.owner = {};
deepMergeInto(data.owner, TA);
const out = JSON.stringify(data, null, 2) + '\n';
fs.writeFileSync(fp, (bom ? '﻿' : '') + out, 'utf8');
console.log('✓ ta:', Object.keys(data.owner).filter(k => typeof data.owner[k] === 'object').length, 'nested keys');