'use strict';

const mongoose = require('mongoose');

const paymentTransactionSchema = new mongoose.Schema(
  {
    // Reference to the monthly rent record
    rentRecordId: {
      type     : mongoose.Schema.Types.ObjectId,
      ref      : 'MonthlyRentRecord',
      required : [true, 'Rent record reference is required'],
    },
    // For quick lookups and filtering
    tenantId: {
      type     : mongoose.Schema.Types.ObjectId,
      ref      : 'Tenant',
      required : [true, 'Tenant reference is required'],
    },
    ownerId: {
      type     : mongoose.Schema.Types.ObjectId,
      ref      : 'User',
      required : [true, 'Owner reference is required'],
    },
    propertyId: {
      type     : mongoose.Schema.Types.ObjectId,
      ref      : 'Property',
      required : [true, 'Property reference is required'],
    },
    
    // ─────────────────────────────────────────────────────────────────────
    // PAYMENT DETAILS
    // ─────────────────────────────────────────────────────────────────────
    // How much was paid in this transaction?
    amount: {
      type    : Number,
      required: [true, 'Amount is required'],
      validate: {
        validator: function(v) {
          if (this.transactionType === 'advance_deducted') return v <= -0.01;
          return v >= 0.01;
        },
        message: props => `Invalid amount ${props.value} for transaction type`
      }
    },
    // How was this payment made?
    paymentMethod: {
      type    : String,
      enum    : ['cash', 'upi', 'bank_transfer', 'cheque', 'other'],
      default : 'cash',
      required: true,
    },
    transactionType: {
      type: String,
      enum: [
        'cash',
        'upi',
        'bank_transfer',
        'cheque',
        'gateway',
        'adjustment',
        'waiver',
        'advance_applied',
        'advance_deducted'
      ],
      default: 'cash',
      required: true
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: function() {
        return this.recordedBy;
      }
    },
    createdByRole: {
      type: String,
      enum: ['tenant', 'owner', 'admin', 'system'],
      default: 'system'
    },
    entrySource: {
      type: String,
      enum: [
        'tenant_upload',
        'owner_manual',
        'admin_manual',
        'auto_adjustment',
        'gateway_callback',
        'system_generated'
      ],
      default: 'system_generated'
    },
    // Reference ID for tracking (e.g., UPI ref, bank transfer ID, cheque number)
    transactionId: {
      type : String,
      trim : true,
      default: null,
    },
    // URL of payment proof (screenshot, receipt, etc.)
    proofImage: {
      secureUrl: { type: String, default: null },
      publicId : { type: String, default: null },
    },
    
    // ─────────────────────────────────────────────────────────────────────
    // METADATA & RELIABILITY
    // ─────────────────────────────────────────────────────────────────────
    // Unique key generated by client to prevent duplicate charges on network retry
    idempotencyKey: {
      type: String,
      trim: true,
      default: null,
    },
    // Who recorded this payment? (owner or superadmin)
    recordedBy: {
      type : mongoose.Schema.Types.ObjectId,
      ref  : 'User',
      required: true,
    },
    // When was this payment made? (may differ from created timestamp)
    paymentDate: {
      type: Date,
      default: Date.now,
      required: true,
    },
    // Any notes about this transaction (editable)
    note: {
      type     : String,
      trim     : true,
      maxlength: [300, 'Note cannot exceed 300 characters'],
    },
    // Admin-specific comments (editable)
    adminComment: {
      type     : String,
      trim     : true,
      maxlength: [500, 'Admin comment cannot exceed 500 characters'],
    },
    
    // ─────────────────────────────────────────────────────────────────────
    // STATUS
    // ─────────────────────────────────────────────────────────────────────
    // For future: allows marking a transaction as reversed or adjusted
    status: {
      type    : String,
      enum    : ['completed', 'reversed', 'failed', 'verifying', 'superseded', 'voided'],
      default : 'completed',
    },
    // If reversed or failed, why?
    statusReason: {
      type: String,
      trim: true,
      maxlength: [300, 'Status reason cannot exceed 300 characters'],
    },

    // ─────────────────────────────────────────────────────────────────────
    // PAYMENT GATEWAY FIELDS (Cashfree, etc.)
    // ─────────────────────────────────────────────────────────────────────
    paymentGateway: {
      type: String,
      enum: ['cashfree', 'razorpay', 'manual', null],
      default: null,
    },
    cashfreeOrderId: {
      type: String,
      default: null,
    },
    cashfreePaymentId: {
      type: String,
      default: null,
    },
    verifiedAt: {
      type: Date,
      default: null,
    },
    webhookPayload: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
      select: false, // Don't expose raw webhook payload in normal queries
    },
  },
  {
    timestamps: true,
    optimisticConcurrency: true, // Enables __v checking on save() to prevent race conditions
    toJSON: {
      transform(_doc, ret) {
        delete ret.__v;
        return ret;
      },
    },
  }
);

// ─────────────────────────────────────────────────────────────────────────
// HOOKS
// ─────────────────────────────────────────────────────────────────────────
// Smart Immutability: Prevent editing financial fields after creation
paymentTransactionSchema.pre('save', function () {
  if (!this.isNew) {
    const immutableFields = ['amount', 'paymentMethod', 'paymentDate', 'transactionType'];
    
    immutableFields.forEach((field) => {
      if (this.isModified(field)) {
        throw new Error(`Financial field '${field}' is immutable and cannot be modified.`);
      }
    });

    // Allow transitioning status between completed, reversed, verifying, failed, superseded, and voided
    if (this.isModified('status')) {
      if (!['completed', 'reversed', 'verifying', 'failed', 'superseded', 'voided'].includes(this.status)) {
        throw new Error(`Invalid status transition to '${this.status}'`);
      }
    }
  }
});

// ─────────────────────────────────────────────────────────────────────────
// INDEXES
// ─────────────────────────────────────────────────────────────────────────
// Find all transactions for a rent record
paymentTransactionSchema.index({ rentRecordId: 1 });
// Find all transactions by tenant
paymentTransactionSchema.index({ tenantId: 1 });
paymentTransactionSchema.index({ tenantId: 1, createdAt: -1 });
// Find all transactions by owner
paymentTransactionSchema.index({ ownerId: 1 });
// Prevent duplicate transaction IDs for payment methods that use them
paymentTransactionSchema.index({ transactionId: 1, paymentMethod: 1 }, { sparse: true });
// Enforce idempotency (prevent duplicate network submissions)
paymentTransactionSchema.index(
  { idempotencyKey: 1 },
  {
    unique: true,
    partialFilterExpression: { idempotencyKey: { $type: 'string' } }
  }
);
// Timeline queries
paymentTransactionSchema.index({ paymentDate: -1 });
// Prevent duplicate gateway transactions — one completed record per Cashfree order
paymentTransactionSchema.index(
  { cashfreeOrderId: 1 },
  {
    unique: true,
    sparse: true, // Ignore docs where cashfreeOrderId is null
    partialFilterExpression: { cashfreeOrderId: { $type: 'string' } }
  }
);

module.exports = mongoose.model('PaymentTransaction', paymentTransactionSchema);
